[package]
name = "img"
version = "1.0.0"
edition = "2024"

[features]
default = []
download = []
embed = ["dep:base64"]

[[example]]
name = "color"
path = "src/color.rs"
test = false

[dependencies]
serde_json = "*"
percent-encoding = "*"
cbor4ii = { version = "*", features = ["use_std", "serde1"] }
base64 = { version = "*", default-features = false, optional = true }
dom_query = { version = "*", default-features = false }

[target.'cfg(unix)'.dependencies]
fork = "*"
file-format = "*"

[target.'cfg(all(unix,not(target_os="espidf")))'.dependencies]
termion = "*"

[target.'cfg(target_os = "hermit")'.dependencies]
hermit = { git = "https://github.com/hermit-os/hermit-rs.git", branch = "main" }

[build-dependencies]
serde_json = "*"
cbor4ii = { version = "*", features = ["use_std", "serde1"] }

[dev-dependencies]
# bincode-next = "*"
