[package]
name = "img"
version = "1.0.0"
edition = "2024"

[[example]]
name = "color"
path = "src/color.rs"
test = false
# required-features = ["color"]

[dependencies]
argh = "*"
base64 = { version = "*", default-features = false }
cbor4ii = { version = "*", features = ["serde1", "use_std"] }
dom_query = { version = "*", default-features = false }
fastrand = "*"
percent-encoding = "*"
serde_json = "*"

[dev-dependencies]
# bincode-next = "*"

[build-dependencies]
cbor4ii = { version = "*", features = ["serde1", "use_std"] }
serde_json = "*"

[target.'cfg(target_os = "hermit")'.dependencies]
hermit = { git = "https://github.com/hermit-os/hermit-rs.git", branch = "main" }

[target.'cfg(unix)'.dependencies]
file-format = "*"
fork = "*"
termion = "*"

[features]
default = []
color = []
download = []
