[target.sparcv9-sun-solaris]
image = "ghcr.io/cross-rs/sparcv9-sun-solaris:main"

[target.x86_64-pc-solaris]
image = "ghcr.io/cross-rs/x86_64-pc-solaris:main"

[target.x86_64-unknown-illumos]
image = "ghcr.io/cross-rs/x86_64-unknown-illumos:main"
