[alias]
rr = "run -r"
br = "build -r"
z = "rustc -- -Z"
cf = "clippy -r --fix --allow-no-vcs"
fx = "fix -r --allow-no-vcs"
ndf = "r -r --no-default-features"
all = "r -r --all-features"
s = "b --profile stats"
lto = "build --profile lto"
no = "build --profile no"
bl = "build --lib -r"
ti = "t -- --nocapture"
dr = "doc -r"
ls = "build --profile lto -Zbuild-std=core,alloc,std,proc_macro,libc,compiler_builtins,panic_abort,panic_unwind -Zbuild-std-features=panic_immediate_abort,compiler-builtins-mem --target "
src = "build --profile src -Zbuild-std=core,alloc,std,proc_macro,libc,compiler_builtins,panic_abort,panic_unwind -Zbuild-std-features=panic_immediate_abort,compiler-builtins-mem --target "

[cargo-new]
vcs = "none"

[net]
#offline = true     

#dev
[profile.dev]
rustflags = ["-Cprefer-dynamic", "-Cdebug-assertions", "-Zdwarf-version=4"]
rpath = true
[profile.dev.package."*"]
inherits = "release"
debug = false
strip = true
[profile.dev.build-override]
inherits = "release"
debug = false
strip = true

#test
[profile.test]
inherits = "dev"
[profile.test.package."*"]
inherits = "release"
[profile.test.build-override]
inherits = "release"

#bench
[profile.bench.package."*"]
inherits = "release"
[profile.bench.build-override]
inherits = "release"
[profile.bench]
inherits = "dev"

#release
[profile.release.build-override]
inherits = "release"
[profile.release.package."*"]
inherits = "release"
[profile.release]
rustflags = ["-Cprefer-dynamic", "-Zcombine-cgu"]
strip = true
lto = true
rpath = true
# codegen-units = 1

#lto
[profile.lto]
inherits = "release"
rustflags = [
    "-Clto=fat",
    "-Cprefer-dynamic=n",
    "-Clinker-plugin-lto",
    "-Zsplit-lto-unit",
    "-Zvirtual-function-elimination",
]
panic = "abort"
[profile.lto.build-override]
inherits = "lto"
[profile.lto.package."*"]
inherits = "lto"

#src
[profile.src]
inherits = "lto"
rustflags = ["-Zforce-unstable-if-unmarked"]
[profile.src.build-override]
inherits = "src"
[profile.src.package."*"]
inherits = "src"

#stats
[profile.stats.build-override]
inherits = "release"
[profile.stats.package."*"]
inherits = "release"
[profile.stats]
inherits = "release"
rustflags = ["-Zperf-stats", "-Zmeta-stats"]

#no
[profile.no.build-override]
inherits = "no"
[profile.no.package."*"]
inherits = "no"
[profile.no]
inherits = "release"
rustflags = ["-Zparse-only", "-Zno-analysis", "-Zno-link", "-Zno-codegen"]

[unstable]
check-cfg = ["names", "values", "features", "output"]
avoid-dev-deps = true
dual-proc-macros = true
panic-abort-tests = true
config-include = true
bindeps = true
binary-dep-depinfo = true
profile-rustflags = true
codegen-backend = true
target-applies-to-host = true
host-config = true

[build]
rustflags = [
    "-Ctarget-feature=-crt-static",
    "-Ctarget-cpu=native",
    "-Csymbol-mangling-version=v0",
    "-Coverflow-checks=no",
    "-Copt-level=s",
    "-Cno-redzone",
    "-Clink-self-contained=+linker",

    "-Cllvm-args=--enable-name-compression --debugify-quiet",
    "-Clink-args=-fno-ident -fno-rtti -fno-exceptions -fno-async-exceptions -fno-backtrace -dynamic-lookup -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables",

    "-Zunstable-options",
    "-Ztune-cpu=native",
    "-Zno-profiler-runtime",
    "-Zplt",
    "-Zthinlto",
    "-Zdylib-lto",
    "-Zno-generate-arange-section",
    "-Zdep-info-omit-d-target",
    "-Zpolonius",
    "-Ztrim-diagnostic-paths",
    "-Zoom=abort",
    "-Zthir-unsafeck",
    "-Zshare-generics",
    "-Zmerge-functions=trampolines",
    "-Zinline-mir",
    "-Zinline-in-all-cgus",
    "-Zmir-opt-level=4",
    "-Zpacked-bundled-libs",
    "-Zteach",
    "-Zmaximal-hir-to-mir-coverage",
    "-Zno-jump-tables",
    "-Zno-trait-vptr",
    "-Zterminal-urls",
    "-Zthreads=0",
    "-Zstaticlib-allow-rdylib-deps",
    "-Zstaticlib-prefer-dynamic",
    "-Ztrait-solver=next-coherence",
    # "-Zdebuginfo-compression=zstd",

    "-Aunused",
    "-Anonstandard_style",
    "-Aunexpected_cfgs",
    "-Frust_2018_idioms",
    "-Frust_2018_compatibility",
]
incremental = true
rustc-wrapper = "sccache"

[unstable.gitoxide]
checkout = true
fetch = true
shallow_index = true
shallow_deps = true
internal_use_git2 = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[target.'cfg(all())']
rustflags = [
    "-Ctarget-feature=-crt-static",
    "-Ctarget-cpu=native",
    "-Csymbol-mangling-version=v0",
    "-Coverflow-checks=no",
    "-Copt-level=s",
    "-Cno-redzone",
    "-Clink-self-contained=+linker",

    "-Cllvm-args=--enable-name-compression --debugify-quiet",
    "-Clink-args=-fno-ident -fno-rtti -fno-exceptions -fno-backtrace -dynamic-lookup -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables",

    "-Zunstable-options",
    "-Ztune-cpu=native",
    "-Zno-profiler-runtime",
    "-Zplt",
    "-Zthinlto",
    "-Zdylib-lto",
    "-Zno-generate-arange-section",
    "-Zdep-info-omit-d-target",
    "-Zpolonius",
    "-Ztrim-diagnostic-paths",
    "-Zoom=abort",
    "-Zthir-unsafeck",
    "-Zshare-generics",
    "-Zmerge-functions=trampolines",
    "-Zinline-mir",
    "-Zinline-in-all-cgus",
    "-Zmir-opt-level=4",
    "-Zpacked-bundled-libs",
    "-Zteach",
    "-Zmaximal-hir-to-mir-coverage",
    "-Zno-jump-tables",
    "-Zterminal-urls",
    "-Zthreads=0",
    "-Zstaticlib-allow-rdylib-deps",
    "-Zstaticlib-prefer-dynamic",
    "-Zno-trait-vptr",
    "-Ztrait-solver=next-coherence",
    "-Zpanic-in-drop=abort",
    # "-Zdebuginfo-compression=zstd",

    "-Aunused",
    "-Anonstandard_style",
    "-Aunexpected_cfgs",
    "-Frust_2018_idioms",
    "-Frust_2018_compatibility",
]

[target.'cfg(target_vendor="apple"))']
rustflags = ["-Clinker-flavor=darwin-lld-cc"]

[target.'cfg(target_env="msvc")']
rustflags = ["-Clinker-flavor=msvc-lld"]

[target.'cfg(any(target_env="gnu",target_env="musl"))']
rustflags = ["-Clinker-flavor=gnu-lld-cc"]

[target.'cfg(target_family="wasm")']
rustflags = ["-Clinker-flavor=wasm-lld-cc"]

[target.'cfg(target_arch="aarch64")']
rustflags = ["-Ctarget-cpu=apple-m1", "-Ztune-cpu=apple-m1"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-linux-android]
linker = "x86_64-linux-android-clang"
