[alias]
rr = "run -r"
br = "build -r"
cf = "clippy -r --fix --allow-no-vcs"
ndf = "run -r --no-default-features"
a = "build -r --all-features"
ar = "run -r --all-features"
ss = "build --profile stats"
lto = "build --profile lto"
no = "build --profile no"
bl = "build --lib -r"
tr = "test -r"
dr = "doc -r"
ls = "build --profile lto -Zbuild-std=core,alloc,std,proc_macro,libc,compiler_builtins,panic_abort -Zbuild-std-features=panic_immediate_abort,compiler-builtins-mem --target "
src = "build --profile src --target "

[cargo-new]
vcs = "none"

[net]
#offline = true     

#dev
[profile.dev]
rustflags = ["-Cprefer-dynamic", "-Cdebug-assertions", "-Zdwarf-version=4"]
rpath = true
[profile.dev.package."*"]
inherits = "release"
debug = false
strip = true
[profile.dev.build-override]
inherits = "release"
debug = false
strip = true

#test
[profile.test]
inherits = "dev"
[profile.test.package."*"]
inherits = "release"
debug = false
strip = true
[profile.test.build-override]
inherits = "release"
debug = false
strip = true

#bench
[profile.bench.package."*"]
inherits = "release"
debug = false
strip = true
[profile.bench.build-override]
inherits = "release"
debug = false
strip = true
[profile.bench]
inherits = "dev"

#release
[profile.release.build-override]
inherits = "release"
[profile.release.package."*"]
inherits = "release"
[profile.release]
rustflags = ["-Cprefer-dynamic", "-Zcombine-cgu"]
rpath = true
strip = true
#codegen-units = 1

#lto
[profile.lto]
inherits = "release"
rustflags = [
    "-Cprefer-dynamic=n",
    "-Zsplit-lto-unit",
    "-Zstaticlib-allow-rdylib-deps",
    "-Zstaticlib-prefer-dynamic",
]
lto = true
panic = "abort"
debug = false
strip = true
[profile.lto.build-override]
inherits = "release"
debug = false
strip = true
[profile.lto.package."*"]
inherits = "release"
debug = false
strip = true

#src
[profile.src]
inherits = "lto"
rustflags = [ #"-Zpanic-in-drop=abort",
    "-Zforce-unstable-if-unmarked",
]
lto = true
panic = "abort"
debug = false
strip = true
[profile.src.build-override]
inherits = "src"
debug = false
strip = true
[profile.src.package."*"]
inherits = "src"
debug = false
strip = true

#stats
[profile.stats.build-override]
inherits = "release"
debug = false
[profile.stats.package."*"]
inherits = "release"
debug = false
[profile.stats]
inherits = "release"
rustflags = ["-Zperf-stats", "-Zmeta-stats"]

#no
[profile.no.build-override]
inherits = "no"
debug = false
[profile.no.package."*"]
inherits = "no"
debug = false
[profile.no]
inherits = "release"
rustflags = ["-Zparse-only", "-Zno-analysis", "-Zno-link", "-Zno-codegen"]

[unstable]
check-cfg = ["names", "values", "features", "output"]
avoid-dev-deps = true
dual-proc-macros = true
panic-abort-tests = true
config-include = true
bindeps = true
binary-dep-depinfo = true
profile-rustflags = true
codegen-backend = true
target-applies-to-host = true
host-config = true

build-std = [
    "core",
    "alloc",
    "std",
    "proc_macro",
    "libc",
    "compiler_builtins",
    "panic_abort",
]
build-std-features = ["panic_immediate_abort", "compiler-builtins-mem"]

[host]
rustflags = [
    "-Cprefer-dynamic",
    "-Crpath",
    "-Ctarget-feature=-crt-static",
    "-Ctarget-cpu=native",
    "-Csymbol-mangling-version=v0",
    "-Coverflow-checks=no",
    "-Copt-level=s",
    "-Cno-redzone",
    #"-Clinker-flavor=lld-link",

    "-Cllvm-args=--enable-name-compression --debugify-quiet",
    "-Clink-args=-fno-ident -fno-rtti -fno-exceptions -fno-async-exceptions -fno-backtrace -gz -dynamic-lookup -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables",

    "-Ztune-cpu=native",
    "-Zno-profiler-runtime",
    "-Zthinlto",
    "-Zplt",
    "-Zdylib-lto",
    "-Zno-generate-arange-section",
    "-Zdep-info-omit-d-target",
    "-Zpolonius",
    "-Ztrim-diagnostic-paths",
    "-Zoom=abort",
    "-Zthir-unsafeck",
    "-Zshare-generics",
    "-Zgcc-ld=lld",
    "-Zmerge-functions=trampolines",
    "-Zinline-mir",
    "-Zinline-in-all-cgus",
    "-Zmir-opt-level=4",
    "-Zpacked-bundled-libs",
    "-Zteach",
    "-Zmaximal-hir-to-mir-coverage",
    "-Zno-jump-tables",
    "-Zterminal-urls",
    "-Zthreads=0",
    "-Zlower-impl-trait-in-trait-to-assoc-ty",
    "-Zstaticlib-allow-rdylib-deps",
    "-Zstaticlib-prefer-dynamic",
    #"-Ztrait-solver=next",

    "-Aunused",
    "-Anonstandard_style",
    "-Aunexpected_cfgs",
    "-Frust_2018_idioms",
    "-Frust_2018_compatibility",
]

[unstable.gitoxide]
checkout = true
fetch = true
shallow_index = true
shallow_deps = true
internal_use_git2 = true


[build]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[target.aarch64-apple-darwin]
rustflags = [
    "-Ctarget-cpu=apple-m1",
    "-Ztune-cpu=apple-m1",
]
[target.x86_64-unknown-linux-gnu]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-Ctarget-cpu=apple-m1", "-Ztune-cpu=apple-m1"]

[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = ["-Zgcc-ld="]

[target.aarch64-pc-windows-msvc]
rustflags = ["-Ctarget-cpu=apple-m1", "-Ztune-cpu=apple-m1"]
