[alias]
ad = "add --no-default-features --optional"
br = "b -r"
dr = "d -r --no-deps"
rr = "r -r"
re = "r --example"
rb = "r --bin"

cf = "clippy --fix --allow-no-vcs --no-deps"
fx = "fix --allow-no-vcs"

ndf = "r --no-default-features"
all = "r --all-features"

tn = "tree -e normal"
ti = "t -- --exact --nocapture"

l = "b --profile lto"

h = "b --profile src -Zbuild-std=core,std,alloc,proc_macro,panic_abort -Zbuild-std-features=panic_immediate_abort --target x86_64h-apple-darwin"
e = "b --profile src -Zbuild-std=core,std,alloc,proc_macro,panic_abort -Zbuild-std-features=panic_immediate_abort --target arm64e-apple-darwin"
s = "b --profile src -Zbuild-std=core,std,alloc,proc_macro,panic_abort -Zbuild-std-features=panic_immediate_abort --target "
z = "zigbuild --profile src -Zbuild-std=core,std,alloc,proc_macro,panic_abort -Zbuild-std-features=panic_immediate_abort --target "


[cargo-new]
vcs = "none"

[env]
RUST_BACKTRACE = "0"
RUST_LIB_BACKTRACE = "0"
RUST_PANIC_STRATEGY = "abort"
RUSTC_ICE = "0"

[net]
#offline = true

#dev
[profile.dev]
rustflags = [
    "-Cprefer-dynamic",
    "-Cdebug-assertions",
    "-Zlocation-detail=file,line,column",
    "-Zcodegen-backend=cranelift",
]
rpath = true
codegen-backend = "cranelift"
debug = false
strip = true
trim-paths = true
[profile.dev.package."*"]
rustflags = ["-Cprefer-dynamic"]
inherits = "dev"
debug-assertions = false
[profile.dev.build-override]
rustflags = ["-Cprefer-dynamic"]
inherits = "dev"
debug-assertions = false

#test
[profile.test]
inherits = "dev"
[profile.test.package."*"]
inherits = "test"
[profile.test.build-override]
inherits = "test"

#bench
[profile.bench.package."*"]
inherits = "bench"
[profile.bench.build-override]
inherits = "bench"
[profile.bench]
inherits = "dev"

#release
[profile.release.build-override]
inherits = "release"
[profile.release.package."*"]
inherits = "release"
[profile.release]
rustflags = ["-Cprefer-dynamic"]
lto = true
rpath = true
codegen-units = 1
trim-paths = true

#lto
[profile.lto]
inherits = "release"
rustflags = ["-Zcross-crate-inline-threshold=yes"]
panic = "abort"
[profile.lto.build-override]
inherits = "lto"
[profile.lto.package."*"]
inherits = "lto"

#src
[profile.src]
inherits = "lto"
rustflags = ["-Cforce-frame-pointers=no", "-Zforce-unstable-if-unmarked"]
[profile.src.build-override]
inherits = "src"
[profile.src.package."*"]
inherits = "src"

[unstable]
avoid-dev-deps = true
dual-proc-macros = true
panic-abort-tests = true
config-include = true
bindeps = true
binary-dep-depinfo = true
profile-rustflags = true
codegen-backend = true
target-applies-to-host = true
host-config = true
trim-paths = true
gc = true
git = { shallow_index = true, shallow_deps = true }
gitoxide = { checkout = true, fetch = true, internal_use_git2 = true }
public-dependency = true
cargo-lints = true

# build-std = [
#     "core",
#     "std",
#     "alloc",
#     "proc_macro",
#     "panic_abort",
#     "libc",
#     "compiler_builtins",
# ]
# build-std-features = ["panic_immediate_abort", "compiler-builtins-mem"]

[host]
rustflags = ["-Ctarget-cpu=native", "-Ztune-cpu=native"]

[build]
incremental = true
rustc-wrapper = "sccache"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[target.'cfg(all())']
rustflags = [
    "-Ctarget-feature=-crt-static",
    "-Csymbol-mangling-version=hashed",
    "-Coverflow-checks=no",
    "-Cforce-frame-pointers=no",
    "-Copt-level=s",
    "-Cno-redzone",
    "-Cdebuginfo=0",
    "-Cstrip=symbols",
    "-Ccollapse-macro-debuginfo=y",
    "-Clink-self-contained=+linker",

    "-Clink-args=-fno-ident -fno-rtti -fno-exceptions -fno-backtrace -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -fPIE",

    "-Zunstable-options",
    "-Zexport-executable-symbols",
    "-Zno-profiler-runtime",
    "-Zlocation-detail=none",
    "-Zplt",
    "-Zthinlto",
    "-Zdylib-lto",
    "-Zno-generate-arange-section",
    "-Zdep-info-omit-d-target",
    "-Zpolonius",
    "-Ztrim-diagnostic-paths",
    "-Zoom=abort",
    "-Zshare-generics",
    "-Zmerge-functions=trampolines",
    "-Zinline-mir",
    "-Zinline-mir-preserve-debug=n",
    "-Zinline-in-all-cgus",
    "-Zcombine-cgu",
    "-Zmir-opt-level=5",
    "-Zpacked-bundled-libs",
    "-Zmaximal-hir-to-mir-coverage",
    "-Zno-jump-tables",
    "-Zterminal-urls",
    "-Zthreads=0",
    "-Zstaticlib-allow-rdylib-deps",
    "-Zstaticlib-prefer-dynamic",
    "-Zno-trait-vptr",
    "-Znext-solver=coherence",
    "-Zpanic-in-drop=abort",
    "-Zcross-crate-inline-threshold=yes",
    "-Zuse-sync-unwind",
    "-Zno-implied-bounds-compat",
    "-Zgraphviz-dark-mode",
    "-Zhas-thread-local",
    "-Zshell-argfiles",
    "-Zub-checks=off",
    "-Zlinker-features=+lld",

    "-Anonstandard_style",
    "-Adead_code",
    "-Aclippy::tabs_in_doc_comments",
    "-Dclippy::redundant_clone",
    "-Dclippy::unused_io_amount",
    "-Frust_2018_idioms",
    "-Frust_2018_compatibility",
]

[target.'cfg(target_vendor="apple")']
rustflags = ["-Clink-arg=-undefined dynamic_lookup"]

[target.'cfg(any(target_vendor="apple",target_os="windows"))']
rustflags = ["-Clink-arg=-fno-async-exceptions"]

[target.'cfg(target_arch="x86_64")']
rustflags = ["-Ctarget-cpu=x86-64-v3", "-Ztune-cpu=x86-64-v3"]

[target.'cfg(all(target_arch="aarch64",target_vendor="apple"))']
rustflags = ["-Ctarget-cpu=apple-m1", "-Ztune-cpu=apple-m1"]

[target.'cfg(all(target_arch="aarch64",target_os="linux"))']
linker = "aarch64-linux-gnu-gcc"

[target.'cfg(all(target_arch="s390x",target_os="linux"))']
linker = "s390x-linux-gnu-gcc"

[target.'cfg(all(target_arch="powerpc64",target_os="linux"))']
linker = "powerpc64-linux-gnu-gcc"

[target.'cfg(all(target_arch="riscv64",target_os="linux"))']
linker = "riscv64-linux-gnu-gcc"

[target.'cfg(all(target_arch="sparc64",target_os="linux"))']
rustflags = ["-Zlinker-features=-lld"]
linker = "sparc64-linux-gnu-gcc"

[target.'cfg(all(target_arch="mips64",target_os="linux"))']
linker = "mips64-linux-gnuabi64-gcc"

[target.'cfg(any(target_os="linux",target_os="android"))']
rustflags = ["-Zrelax-elf-relocations"]

[target.'cfg(target_os="android")']
rustflags = ["-Zhas-thread-local=no"]

[target.sparcv9-sun-solaris]
linker = "sparcv9-solaris-gcc"
ar = "sparcv9-solaris-ar"

[target.powerpc64-ibm-aix]
linker = "powerpc64-linux-gnu-gcc"

[target.arm64ec-pc-windows-msvc]
linker = "link.exe"
rustflags = ["-Clink-arg=/MACHINE:ARM64EC"]

# [target.s390x-unknown-linux-musl]
# linker = "/usr/bin/musl-cross-make"
