name: Build

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Android-x86_64
            os: ubuntu-latest
            target: x86_64-linux-android
            bin: Img
            name: Android-x86_64
            command: build
            toolchain: nightly

          - release_for: Android-AArch64
            os: ubuntu-latest
            target: aarch64-linux-android
            bin: Img
            name: Android-AArch64
            command: build
            toolchain: nightly

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Purge Ubuntu
        run: |
          sudo apt purge ufw rsyslog logrotate sysstat python3-problem-report sosreport apport

          sudo systemctl mask systemd-journald.service systemd-journald.socket

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--profile src -Zbuild-std=core,alloc,std,proc_macro,libc,compiler_builtins,panic_abort,panic_unwind -Zbuild-std-features=panic_immediate_abort,compiler-builtins-mem"
          strip: true
      
      - name: Upload ${{ matrix.platform.name }} to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.platform.target }}/src/Img
          asset_name: ${{ matrix.platform.name }}
          tag: Nightly
          overwrite: true
          body: "${{ matrix.platform.name }}"
