name: Android

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Building on Ubuntu.
    runs-on: ubuntu-latest

    steps:
      - name: Purge Ubuntu
        run: |
          sudo apt purge ufw rsyslog logrotate sysstat python3-problem-report sosreport apport

          sudo systemctl mask systemd-journald.service systemd-journald.socket

      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-linux-android,aarch64-linux-android
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Android NDK setup
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          link-to-sdk: true
          local-cache: true

      - name: Build Release
        run: |
          cargo binstall cargo-ndk -y

          cargo update

          time cargo ndk -t x86_64-linux-android -t aarch64-linux-android b --profile src -Zbuild-std=core,std,alloc,proc_macro,panic_abort -Zbuild-std-features=panic_immediate_abort

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload Android-x86_64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-linux-android/src/Img
          asset_name: Android-x86_64
          tag: Nightly
          overwrite: true
          body: "Android-x86_64 binary executable."

      - name: Upload Android-AArch64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/aarch64-linux-android/src/Img
          asset_name: Android-AArch64
          tag: Nightly
          overwrite: true
          body: "Android-AArch64 binary executable."
