name: Stable

on:
  push:
    branches: ["stable"]
  pull_request:
    branches: ["stable"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Ubuntu-24.04-arm
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latest stable build ID
        id: ver
        run: |
          rust=$(curl -s https://static.rust-lang.org/dist/channel-rust-stable.toml \
            | sed -n '/^\[pkg.rust\]/,/^\[pkg\./p' \
            | grep '^version' \
            | cut -d'"' -f2)
          echo $rust
          echo "rust=$rust" >> $GITHUB_OUTPUT

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-${{ runner.arch }}-stable-${{ steps.ver.outputs.rust}}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-stable-

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu,aarch64-unknown-linux-musl,riscv64gc-unknown-linux-gnu,riscv64gc-unknown-linux-musl,s390x-unknown-linux-gnu,powerpc64le-unknown-linux-gnu,sparc64-unknown-linux-gnu,loongarch64-unknown-linux-gnu,loongarch64-unknown-linux-musl

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Ubuntu apt update and install
        continue-on-error: true
        run: |
          sudo apt update -q && sudo apt install -q gcc-riscv64-linux-gnu gcc-s390x-linux-gnu gcc-powerpc64le-linux-gnu gcc-sparc64-linux-gnu gcc-14-loongarch64-linux-gnu musl-tools -y

      - name: Build Release
        run: |
          cargo update
          set +e -x

          targets=(
            powerpc64le-unknown-linux-gnu
            riscv64gc-unknown-linux-gnu
            riscv64gc-unknown-linux-musl
            aarch64-unknown-linux-gnu
            aarch64-unknown-linux-musl
            sparc64-unknown-linux-gnu
            s390x-unknown-linux-gnu
            loongarch64-unknown-linux-gnu
            loongarch64-unknown-linux-musl
          )

          for target in ${targets[@]}; do
            time cargo l --target $target
          done

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "powerpc64le-unknown-linux-gnu Linux-powerpc64le-gnu"
                  "riscv64gc-unknown-linux-gnu Linux-riscv64gc-gnu"
                  "riscv64gc-unknown-linux-musl Linux-riscv64gc-musl"
                  "aarch64-unknown-linux-gnu Linux-aarch64-gnu"
                  "aarch64-unknown-linux-musl Linux-aarch64-musl"
                  "sparc64-unknown-linux-gnu Linux-sparc64-gnu"
                  "s390x-unknown-linux-gnu Linux-s390x-gnu"
                  "loongarch64-unknown-linux-gnu Linux-loongarch64-gnu"
                  "loongarch64-unknown-linux-musl Linux-loongarch64-musl"
          )
          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/lto/Img target/$arch/lto/$name || true
            gh release upload Stable target/$arch/lto/$name --clobber || true
          done

  Android:
    name: Ubuntu-24.04
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latest stable build ID
        id: ver
        run: |
          rust=$(curl -s https://static.rust-lang.org/dist/channel-rust-stable.toml \
            | sed -n '/^\[pkg.rust\]/,/^\[pkg\./p' \
            | grep '^version' \
            | cut -d'"' -f2)
          echo $rust
          echo "rust=$rust" >> $GITHUB_OUTPUT

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-${{ runner.arch }}-stable-${{ steps.ver.outputs.rust}}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-stable-

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-linux-android,aarch64-linux-android,armv7-linux-androideabi,powerpc64-unknown-linux-gnu,x86_64-unknown-linux-gnu,x86_64-unknown-linux-musl

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Get latest Android NDK version
        id: ndk-ver
        run: |
          latest_ndk=$(curl -fsSL https://developer.android.com/ndk/downloads \
            | sed -n 's/.*Latest Stable Version (\([^)]*\)).*/\1/p')
          echo "NDK_VERSION=$latest_ndk" >> $GITHUB_ENV
          echo "Latest NDK: $latest_ndk"

      - name: Android NDK cache
        uses: actions/cache@v4
        with:
          path: ~/android-ndk
          key: android-ndk-${{ env.NDK_VERSION }}

      - name: Ubuntu apt update and install
        continue-on-error: true
        run: sudo apt update -q && sudo apt install gcc-powerpc64-linux-gnu musl-tools -qy

      - name: Build Release
        run: |
          cargo update
          set +e -x

          ver=${NDK_VERSION}
          export ANDROID_NDK_HOME=~/android-ndk/android-ndk-$ver
          ln -sf "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/" sysroot

          if [ ! -d ~/android-ndk ]; then
            mkdir -p ~/android-ndk
            echo "Downloading Android NDK..."
            curl -fsSLO https://dl.google.com/android/repository/android-ndk-$ver-linux.zip
            echo "Unzipping Android NDK..."
            unzip -q android-ndk-$ver-linux.zip -d ~/android-ndk
          fi

          ln -sf $(readlink sysroot)/sysroot $(readlink sysroot)/android

          targets=(
            x86_64-unknown-linux-gnu
            x86_64-unknown-linux-musl
            aarch64-linux-android
            armv7-linux-androideabi
            x86_64-linux-android
            powerpc64-unknown-linux-gnu
          )

          for target in ${targets[@]}; do
            time cargo l --target $target
          done

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "x86_64-linux-android Android-x86_64"
                  "aarch64-linux-android Android-aarch64"
                  "armv7-linux-androideabi Android-armv7"
                  "powerpc64-unknown-linux-gnu Linux-powerpc64-gnu"
                  "x86_64-unknown-linux-gnu Linux-x86_64-gnu"
                  "x86_64-unknown-linux-musl Linux-x86_64-musl"
          )
          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/lto/Img target/$arch/lto/$name || true
            gh release upload Stable target/$arch/lto/$name --clobber || true
          done

  macOS:
    name: macOS-15
    runs-on: macos-15

    steps:
      - name: Disable macos spotlight index
        run: |
          sudo mdutil -a -i off
          sudo mdutil -a -d
          sudo pmset -a powernap 0
          sudo pmset -a sleep 0

      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latest stable build ID
        id: ver
        run: |
          rust=$(curl -s https://static.rust-lang.org/dist/channel-rust-stable.toml \
            | sed -n '/^\[pkg.rust\]/,/^\[pkg\./p' \
            | grep '^version' \
            | cut -d'"' -f2)
          echo $rust
          echo "rust=$rust" >> $GITHUB_OUTPUT

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-${{ runner.arch }}-stable-${{ steps.ver.outputs.rust}}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-stable-

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-ios,wasm32-wasip2

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Build Release
        run: |
          cargo update
          set +e -x
          targets=(
            aarch64-apple-darwin
            aarch64-apple-ios
            x86_64-apple-darwin
            wasm32-wasip2
          )
          for target in ${targets[@]}; do
            time cargo l --target $target
          done

          lipo -create target/aarch64-apple-darwin/lto/Img target/x86_64-apple-darwin/lto/Img -output Img-Universal

          find . \( -iname img -o -iname img.wasm -o -iname Img-Universal \) -type f | xargs ls -hl
          sw_vers
          hostinfo
          sysctl -a | grep brand

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "x86_64-apple-darwin Apple-macOS-x86_64"
                  "aarch64-apple-darwin Apple-macOS-aarch64"
                  "aarch64-apple-ios Apple-iOS-aarch64"
          )

          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/lto/Img target/$arch/lto/$name || true
            gh release upload Stable target/$arch/lto/$name --clobber || true
          done

          echo "Uploading wasm32-wasip2.wasm..."
          gh release upload Stable target/wasm32-wasip2/lto/Img.wasm#wasm32-wasip2.wasm --clobber || true
          echo "Uploading Apple-macOS-universal..."
          gh release upload Stable Img-Universal#Apple-macOS-universal --clobber || true

  Windows-2025:
    name: Windows-2025
    runs-on: windows-2025

    steps:
      - name: Disable and Stop windows services
        continue-on-error: true
        run: |
          $ErrorActionPreference = 'Ignore'

          $pattern = "maint|diag|exper|search|logs|assist|report|logg|defend";
          $services = Get-Service|? DisplayName -match $pattern

          $services | Set-Service -StartMode Disabled -ErrorAction SilentlyContinue
          $services | Stop-Service -Force

          $services | % {$_.DisplayName; $_.Status}

          reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo" /v Enabled /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v Disabled /t REG_DWORD /d 1 /f

          Get-ScheduledTask | Disable-ScheduledTask -Confirm:$false
          Get-ScheduledTask | Unregister-ScheduledTask -Confirm:$false

      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latest stable build ID
        id: ver
        run: |
          $url = 'https://static.rust-lang.org/dist/channel-rust-stable.toml'
          $toml = Invoke-RestMethod -Uri $url

          $pattern = '\[pkg\.rust\][\s\S]*?version\s*=\s*"(.*?)"'
          $m = [regex]::Match($toml, $pattern)

          $ver = $m.Groups[1].Value
          Write-Host "Found Rust stable version: $ver"

          "rust=$ver" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-${{ runner.arch }}-stable-${{ steps.ver.outputs.rust}}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-stable-

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-pc-windows-msvc,arm64ec-pc-windows-msvc
          # components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Build release
        continue-on-error: true
        run: |
          cargo update
          $targets = @(
                      "aarch64-pc-windows-msvc",
                      "x86_64-pc-windows-msvc",
                      "arm64ec-pc-windows-msvc"
                    )
          foreach ($target in $targets) {
              Write-Host "Building: $target"
              Measure-Command { cargo l --target $target }
          }

          Get-ChildItem -Path target\*\lto\Img.exe -File
          systeminfo

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
        run: |
          $targets = @(
              @("aarch64-pc-windows-msvc", "Windows-aarch64.exe"),
              @("x86_64-pc-windows-msvc", "Windows-x86_64.exe"),
              @("arm64ec-pc-windows-msvc", "Windows-arm64ec.exe")
          )

          foreach ($target in $targets) {
              $arch = $target[0]
              $name = $target[1]
              Write-Host "Uploading $name..."
              Move-Item target/$arch/lto/Img.exe target/$arch/lto/$name; $?
              gh release upload Stable target/$arch/lto/$name --clobber; $?
          }

  Windows-11-Arm:
    name: Windows-11-arm
    runs-on: windows-11-arm

    steps:
      - name: Disable and Stop windows services
        continue-on-error: true
        run: |
          $ErrorActionPreference = 'Ignore'

          $pattern = "maint|diag|exper|search|logs|assist|report|logg|defend";
          $services = Get-Service|? DisplayName -match $pattern

          $services | Set-Service -StartMode Disabled -ErrorAction SilentlyContinue
          $services | Stop-Service -Force

          $services | % {$_.DisplayName; $_.Status}

          reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo" /v Enabled /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v Disabled /t REG_DWORD /d 1 /f

          Get-ScheduledTask | Disable-ScheduledTask -Confirm:$false
          Get-ScheduledTask | Unregister-ScheduledTask -Confirm:$false

      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latest stable build ID
        id: ver
        run: |
          $url = 'https://static.rust-lang.org/dist/channel-rust-stable.toml'
          $toml = Invoke-RestMethod -Uri $url

          $pattern = '\[pkg\.rust\][\s\S]*?version\s*=\s*"(.*?)"'
          $m = [regex]::Match($toml, $pattern)

          $ver = $m.Groups[1].Value
          Write-Host "Found Rust stable version: $ver"

          "rust=$ver" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-${{ runner.arch }}-stable-${{ steps.ver.outputs.rust}}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-stable-

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc,arm64ec-pc-windows-msvc
          # components: rust-src

      # - name: Run sccache-cache
      #   uses: mozilla-actions/sccache-action@main

      - name: Build release
        continue-on-error: true
        run: |
          Remove-Item Env:SCCACHE_GHA_ENABLED
          Remove-Item Env:RUSTC_WRAPPER

          cargo update
          $targets = @(
                      "aarch64-pc-windows-msvc",
                      "x86_64-pc-windows-msvc",
                      "arm64ec-pc-windows-msvc"
                    )
          foreach ($target in $targets) {
              Write-Host "Building: $target"
              Measure-Command { cargo l --target $target }
          }

          Get-ChildItem -Path target\*\lto\Img.exe -File
          systeminfo

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
        run: |
          $targets = @(
              @("aarch64-pc-windows-msvc", "Windows-aarch64.exe"),
              @("x86_64-pc-windows-msvc", "Windows-x86_64.exe"),
              @("arm64ec-pc-windows-msvc", "Windows-arm64ec.exe")
          )

          foreach ($target in $targets) {
              $arch = $target[0]
              $name = $target[1]
              Write-Host "Uploading $name..."
              Move-Item target/$arch/lto/Img.exe target/$arch/lto/$name; $?
              gh release upload Stable target/$arch/lto/$name --clobber; $?
          }
