name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Linux:
    name: Building on Ubuntu. 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Rust Update
      run: |
        rustup default nightly
        rustup update
        sudo apt install gcc-aarch64-linux-gnu -y
        rustup target add aarch64-unknown-linux-gnu
        rustup component add rust-src
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      
    - name: Build Release
      run: |
        cargo update
        #time cargo build --release
        #time cargo lto
        time cargo src x86_64-unknown-linux-gnu
        time cargo src aarch64-unknown-linux-gnu
        #ls -hl target/*/BL
        ls -hl target/*/*/BL
        lscpu
        free -m
        
    - name: Rust Versions
      run: rustup -V; cargo -Vv; rustc -Vv
      
    - name: Upload Linux x64 to a GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/x86_64-unknown-linux-gnu/src/BL
        asset_name: Linux
        tag: Nightly
        overwrite: true
        body: "Ubuntu Linux binary executable."

    - name: Upload Linux-arm64e to a GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/aarch64-unknown-linux-gnu/src/BL
        asset_name: Linux-arm64e
        tag: Nightly
        overwrite: true
        body: "Ubuntu Linux-arm64e binary executable."
          
  macOS:
    name: Building on macOS. 
    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Rust Update
      run: |
        brew uninstall rustup && brew autoremove
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs|sh -s -- --default-toolchain nightly -y 
        rustup target add aarch64-apple-darwin
        rustup component add rust-src
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    
    - name: Build Release
      run: |
        cargo update
        #time cargo build --release
        #time cargo lto
        time cargo src x86_64-apple-darwin
        time cargo src aarch64-apple-darwin
        lipo -create target/aarch64-apple-darwin/src/BL target/x86_64-apple-darwin/src/BL -output BL-universal
        #ls -hl target/*/BL
        ls -hl target/x86_64-apple-darwin/*/BL
        ls -hl target/aarch64-apple-darwin/*/BL
        ls -hl BL-universal
        sw_vers
        hostinfo
        sysctl -a | grep brand
        
    - name: Rust Versions
      run: rustup -V; cargo -Vv; rustc -Vv
      
    - name: Upload macOS x86-64 to a GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/x86_64-apple-darwin/src/BL
        asset_name: macOS-intel
        tag: Nightly
        overwrite: true
        body: "macOS x86-64 binary executable."

        
    - name: Upload macOS-arm64e to a GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/aarch64-apple-darwin/src/BL
        asset_name: macOS-arm64e
        tag: Nightly
        overwrite: true
        body: "macOS arm64e binary executable."

    - name: Upload macOS-universal to a GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: BL-universal
        asset_name: macOS-universal
        tag: Nightly
        overwrite: true
        body: "macOS universal binary executable."
        
      
  Windows:
    name: Building on Windows. 
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Rust Update
      run: |
        rustup default nightly
        rustup update
        rustup target add aarch64-pc-windows-msvc
        rustup component add rust-src
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      
    - name: Build release
      run: |
        cargo update
        #cargo build --release
        #cargo lto
        cargo src x86_64-pc-windows-msvc
        cargo src aarch64-pc-windows-msvc
        #dir target/*/*.exe
        dir target/*/*/*.exe
        systeminfo
        
    - name: Rust Versions
      run: rustup -V; cargo -Vv; rustc -Vv
      
    - name: Upload Windows-x64 to a GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/x86_64-pc-windows-msvc/src/BL.exe
        asset_name: Windows.exe
        tag: Nightly
        overwrite: true
        body: "Windows x64 binary executable."

    - name: Upload Windows-arm64e to a GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/aarch64-pc-windows-msvc/src/BL.exe
        asset_name: Windows-arm64e.exe
        tag: Nightly
        overwrite: true
        body: "Windows arm64e binary executable."
