name: Stable

on:
  push:
    branches: ["stable"]
  pull_request:
    branches: ["stable"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Ubuntu-24.04-arm
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu,x86_64-unknown-linux-musl,x86_64-unknown-linux-gnux32,aarch64-unknown-linux-gnu,aarch64-unknown-linux-musl,riscv64gc-unknown-linux-gnu,riscv64gc-unknown-linux-musl,s390x-unknown-linux-gnu,powerpc64le-unknown-linux-gnu,powerpc64le-unknown-linux-musl,sparc64-unknown-linux-gnu,loongarch64-unknown-linux-gnu,loongarch64-unknown-linux-musl,thumbv7neon-unknown-linux-gnueabihf

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Ubuntu apt update and install
        continue-on-error: true
        run: |
          sudo apt update -q && sudo apt install -q gcc-x86-64-linux-gnu gcc-x86-64-linux-gnux32 gcc-riscv64-linux-gnu gcc-s390x-linux-gnu gcc-powerpc64le-linux-gnu gcc-powerpc64-linux-gnu gcc-sparc64-linux-gnu gcc-14-loongarch64-linux-gnu gcc-arm-linux-gnueabihf musl-tools -y

      - name: Build Release
        run: |
          cargo update
          set +e -x

          targets=(
            x86_64-unknown-linux-gnu
            x86_64-unknown-linux-musl
            x86_64-unknown-linux-gnux32
            powerpc64le-unknown-linux-gnu
            powerpc64le-unknown-linux-musl
            powerpc64-unknown-linux-musl
            riscv64gc-unknown-linux-gnu
            riscv64gc-unknown-linux-musl
            aarch64-unknown-linux-gnu
            aarch64-unknown-linux-musl
            sparc64-unknown-linux-gnu
            s390x-unknown-linux-gnu
            thumbv7neon-unknown-linux-gnueabihf
            loongarch64-unknown-linux-gnu
            loongarch64-unknown-linux-musl
          )

          for target in ${targets[@]}; do
            time cargo l $target
          done

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: Linux-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
            x86_64-unknown-linux-gnu
            x86_64-unknown-linux-musl
            x86_64-unknown-linux-gnux32
            powerpc64le-unknown-linux-gnu
            powerpc64le-unknown-linux-musl
            powerpc64-unknown-linux-musl
            riscv64gc-unknown-linux-gnu
            riscv64gc-unknown-linux-musl
            aarch64-unknown-linux-gnu
            aarch64-unknown-linux-musl
            sparc64-unknown-linux-gnu
            s390x-unknown-linux-gnu
            thumbv7neon-unknown-linux-gnueabihf
            loongarch64-unknown-linux-gnu
            loongarch64-unknown-linux-musl
          )
          for target in "${targets[@]}"; do
            IFS='-' read -r arch vendor os rest <<< "$target"
            os_cap="${os^}"
            if [[ -n "$rest" ]]; then
                name="${os_cap}-${arch}-${rest}"
              else
                name="${os_cap}-${arch}"
              fi
            echo "Uploading $name..."
            mv target/$target/lto/img target/$target/lto/$name || true
            gh release upload Stable target/$target/lto/$name --clobber || true
          done

  Android:
    name: Ubuntu-24.04
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-linux-android,aarch64-linux-android,armv7-linux-androideabi,thumbv7neon-linux-androideabi,powerpc64-unknown-linux-gnu,aarch64-unknown-linux-ohos,armv7-unknown-linux-ohos,x86_64-unknown-linux-ohos,x86_64-unknown-redox

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Get latest Android NDK version
        run: |
          latest_ndk=$(curl -fsSL https://developer.android.com/ndk/downloads \
            | sed -n 's/.*Latest Stable Version (\([^)]*\)).*/\1/p')
          echo "NDK_VERSION=$latest_ndk" >> $GITHUB_ENV
          echo "Latest NDK: $latest_ndk"

      - name: Android NDK cache
        uses: actions/cache@v6
        with:
          path: ~/android-ndk-${{ env.NDK_VERSION }}
          key: android-ndk-${{ env.NDK_VERSION }}
          restore-keys: android-ndk-${{ env.NDK_VERSION }}

      - name: Setup OpenHarmony SDK
        uses: openharmony-rs/setup-ohos-sdk@main
        with:
          version: "6.1"

      - name: Ubuntu apt update and install
        run: sudo apt install gcc-powerpc64-linux-gnu musl-tools libfuse3-dev -qy

      - name: Cache Redoxer
        uses: actions/cache@v6
        with:
          path: |
            ~/.redoxer
            ~/.cargo/bin/redoxer
          key: redoxer
          restore-keys: redoxer

      - name: Build Release
        run: |
          cargo update
          set +e -x

          ver=${NDK_VERSION}
          export ANDROID_NDK_HOME=~/android-ndk-$ver
          ln -sf "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64" ndk

          if [ ! -d ~/android-ndk-${ver} ]; then
            mkdir -p ~/android-ndk-${ver}
            echo "Downloading Android NDK..."
            curl -fsSLO https://dl.google.com/android/repository/android-ndk-${ver}-linux.zip
            echo "Unzipping Android NDK..."
            unzip -q android-ndk-${ver}-linux.zip -d ~/
          fi

          ln -sf $OHOS_SDK_NATIVE/llvm ohos
          ln -sf $OHOS_SDK_NATIVE/sysroot ohos-root

          if [ ! -f ~/.cargo/bin/redoxer ]; then
            cargo install --git https://gitlab.redox-os.org/redox-os/redoxer.git redoxer -q --locked --force
          fi
          if [ ! -d ~/.redoxer ]; then
            redoxer toolchain
          fi

          targets=(
            x86_64-unknown-redox
          )
          for target in ${targets[@]}; do
            time redoxer build -- -q --profile lto --target $target
          done

          targets=(
            aarch64-unknown-linux-ohos
            armv7-unknown-linux-ohos
            x86_64-unknown-linux-ohos
            aarch64-linux-android
            armv7-linux-androideabi
            thumbv7neon-linux-androideabi
            x86_64-linux-android
            powerpc64-unknown-linux-gnu
          )

          for target in ${targets[@]}; do
            time cargo l $target
          done

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: Android-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "x86_64-linux-android Android-x86_64"
                  "aarch64-linux-android Android-aarch64"
                  "armv7-linux-androideabi Android-armv7"
                  "thumbv7neon-linux-androideabi Android-thumbv7neon"
                  "powerpc64-unknown-linux-gnu Linux-powerpc64-gnu"
                  "aarch64-unknown-linux-ohos Android-aarch64-ohos"
                  "armv7-unknown-linux-ohos Android-armv7-ohos"
                  "x86_64-unknown-linux-ohos Android-x86_64-ohos"
                  "x86_64-unknown-redox Redox-x86_64"
          )
          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/lto/img target/$arch/lto/$name || true
            gh release upload Stable target/$arch/lto/$name --clobber || true
          done

  macOS:
    name: macOS-26
    runs-on: macos-26

    steps:
      - name: Disable macos spotlight index
        run: |
          sudo mdutil -a -i off
          sudo mdutil -a -d
          sudo pmset -a powernap 0
          sudo pmset -a sleep 0

      - name: Checkout
        uses: actions/checkout@v7

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-ios,wasm32-wasip2,x86_64-pc-windows-gnullvm,aarch64-pc-windows-gnullvm,x86_64-fortanix-unknown-sgx,aarch64-apple-tvos,aarch64-apple-visionos,aarch64-apple-watchos

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Cache llvm-mingw
        uses: actions/cache@v6
        with:
          path: llvm-mingw
          key: ${{ runner.os }}-llvm-mingw-${{ hashFiles('llvm-mingw/**') }}
          restore-keys: ${{ runner.os }}-llvm-mingw-

      - name: llvm-mingw
        run: |
          if [ ! -d llvm-mingw ]; then
            mkdir llvm-mingw
            curl -LsSf https://github.com/mstorsjo/llvm-mingw/releases/download/20251216/llvm-mingw-20251216-ucrt-macos-universal.tar.xz | tar -xJf - -C llvm-mingw --strip-components=1
          fi
          echo "$PWD/llvm-mingw/bin" >> "$GITHUB_PATH"

      - name: Build Release
        run: |
          cargo update
          set +e -x

          targets=(
            x86_64-fortanix-unknown-sgx
            aarch64-pc-windows-gnullvm
            x86_64-pc-windows-gnullvm
            aarch64-apple-darwin
            aarch64-apple-ios
            x86_64-apple-darwin
            aarch64-apple-tvos
            aarch64-apple-visionos
            aarch64-apple-watchos
            wasm32-wasip2
          )
          for target in ${targets[@]}; do
            time cargo l $target
          done

          lipo -create target/aarch64-apple-darwin/lto/img target/x86_64-apple-darwin/lto/img -output Img-Universal

          find ./target \( -iname img -o -iname img.exe -o -iname img.wasm -o -iname Img-Universal \) -type f | xargs ls -hl
          sw_vers
          hostinfo
          sysctl -a | grep brand

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: Apple-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "x86_64-apple-darwin Apple-macOS-x86_64"
                  "aarch64-apple-darwin Apple-macOS-aarch64"
                  "aarch64-apple-ios Apple-iOS-aarch64"
                  "aarch64-apple-tvos Apple-tvOS"
                  "aarch64-apple-visionos Apple-visionOS"
                  "aarch64-apple-watchos Apple-watchOS"
                  "aarch64-pc-windows-gnullvm Windows-aarch64-gnullvm.exe"
                  "x86_64-pc-windows-gnullvm Windows-x86_64-gnullvm.exe"
                  "wasm32-wasip2 wasm32-wasip2.wasm"
                  "x86_64-fortanix-unknown-sgx Fortanix-sgx"
          )

          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            for f in img img.exe img.wasm; do
                if [ -e "target/$arch/lto/$f" ]; then
                    mv "target/$arch/lto/$f" "target/$arch/lto/$name"
                    break
                fi
            done
            gh release upload Stable target/$arch/lto/$name --clobber || true
          done

          echo "Uploading Apple-macOS-universal..."
          gh release upload Stable Img-Universal#Apple-macOS-universal --clobber || true

  Windows-2025:
    name: Windows-2025
    runs-on: windows-2025

    steps:
      - name: Disable and Stop windows services
        continue-on-error: true
        run: |
          $ErrorActionPreference = 'Ignore'

          $pattern = "maint|diag|exper|search|logs|assist|report|logg|defend";
          $services = Get-Service|? DisplayName -match $pattern

          $services | Set-Service -StartMode Disabled -ErrorAction SilentlyContinue
          $services | Stop-Service -Force

          $services | % {$_.DisplayName; $_.Status}

          reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo" /v Enabled /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v Disabled /t REG_DWORD /d 1 /f

          Get-ScheduledTask | Disable-ScheduledTask -Confirm:$false
          Get-ScheduledTask | Unregister-ScheduledTask -Confirm:$false

      - name: Checkout
        uses: actions/checkout@v7

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-pc-windows-msvc,arm64ec-pc-windows-msvc

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Build release
        continue-on-error: true
        run: |
          cargo update
          $targets = @(
                      "aarch64-pc-windows-msvc",
                      "x86_64-pc-windows-msvc",
                      "arm64ec-pc-windows-msvc"
                    )
          foreach ($target in $targets) {
              Write-Host "Building: $target"
              Measure-Command { cargo l $target }
          }

          Get-ChildItem -Path target\*\lto\img.exe -File
          systeminfo

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: Windows-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
        run: |
          $targets = @(
              @("aarch64-pc-windows-msvc", "Windows-aarch64.exe"),
              @("x86_64-pc-windows-msvc", "Windows-x86_64.exe"),
              @("arm64ec-pc-windows-msvc", "Windows-arm64ec.exe")
          )

          foreach ($target in $targets) {
              $arch = $target[0]
              $name = $target[1]
              Write-Host "Uploading $name..."
              Move-Item target/$arch/lto/img.exe target/$arch/lto/$name; $?
              gh release upload Stable target/$arch/lto/$name --clobber; $?
          }

  Windows-11-Arm:
    name: Windows-11-arm
    runs-on: windows-11-arm

    steps:
      - name: Disable and Stop windows services
        continue-on-error: true
        run: |
          $ErrorActionPreference = 'Ignore'

          $pattern = "maint|diag|exper|search|logs|assist|report|logg|defend";
          $services = Get-Service|? DisplayName -match $pattern

          $services | Set-Service -StartMode Disabled -ErrorAction SilentlyContinue
          $services | Stop-Service -Force

          $services | % {$_.DisplayName; $_.Status}

          reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo" /v Enabled /t REG_DWORD /d 0 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v Disabled /t REG_DWORD /d 1 /f

          Get-ScheduledTask | Disable-ScheduledTask -Confirm:$false
          Get-ScheduledTask | Unregister-ScheduledTask -Confirm:$false

      - name: Checkout
        uses: actions/checkout@v7

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc,arm64ec-pc-windows-msvc

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      # - name: Run sccache-cache
      #   uses: mozilla-actions/sccache-action@main

      - name: Build release
        continue-on-error: true
        run: |
          Remove-Item Env:SCCACHE_GHA_ENABLED
          Remove-Item Env:RUSTC_WRAPPER

          cargo update
          $targets = @(
                      "aarch64-pc-windows-msvc",
                      "x86_64-pc-windows-msvc",
                      "arm64ec-pc-windows-msvc"
                    )
          foreach ($target in $targets) {
              Write-Host "Building: $target"
              Measure-Command { cargo l $target }
          }

          Get-ChildItem -Path target\*\lto\img.exe -File
          systeminfo

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: Windows-Arm-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
        run: |
          $targets = @(
              @("aarch64-pc-windows-msvc", "Windows-aarch64.exe"),
              @("x86_64-pc-windows-msvc", "Windows-x86_64.exe"),
              @("arm64ec-pc-windows-msvc", "Windows-arm64ec.exe")
          )

          foreach ($target in $targets) {
              $arch = $target[0]
              $name = $target[1]
              Write-Host "Uploading $name..."
              Move-Item target/$arch/lto/img.exe target/$arch/lto/$name; $?
              gh release upload Stable target/$arch/lto/$name --clobber; $?
          }
