name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Linux:
    name: Building on Ubuntu. 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Rust Update
      run: |
        rustup self update
        rustup default nightly
        rustup update
        rustup component add rust-src clippy
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      
    - name: Build Release
      run: |
        cargo update
        #time cargo build --release
        #time cargo lto
        time cargo src x86_64-unknown-linux-gnu
        #ls -hl target/*/BL
        ls -hl target/*/*/BL
        lscpu
        free -m
        
    - name: Rust Versions
      run: rustup -V; cargo -Vv; rustc -Vv
      
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/x86_64-unknown-linux-gnu/src/BL
        asset_name: Linux
        tag: Nightly
        overwrite: true
        body: "Ubuntu Linux binary executable."
          
  macOS:
    name: Building on macOS. 
    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Rust Update
      run: |
        brew uninstall rustup||brew autoremove
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y 1 --default-toolchain nightly | sh 
        rustup component add rust-src clippy
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    
    - name: Build Release
      run: |
        cargo update
        #time cargo build --release
        #time cargo lto
        time cargo src x86_64-apple-darwin
        #ls -hl target/*/BL
        ls -hl target/*/*/BL
        sw_vers
        hostinfo
        sysctl -a | grep brand
        
    - name: Rust Versions
      run: rustup -V; cargo -Vv; rustc -Vv
      
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/x86_64-apple-darwin/src/BL
        asset_name: macOS
        tag: Nightly
        overwrite: true
        body: "macOS binary executable."
      
  Windows:
    name: Building on Windows. 
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Rust Update
      run: |
        rustup self update
        rustup default nightly
        rustup update
        rustup component add rust-src clippy
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      
    - name: Build release
      run: |
        cargo update
        #cargo build --release
        #cargo lto
        cargo src x86_64-pc-windows-msvc
        #dir target/*/*.exe
        dir target/*/*/*.exe
        systeminfo
        
    - name: Rust Versions
      run: rustup -V; cargo -Vv; rustc -Vv
      
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/x86_64-pc-windows-msvc/src/BL.exe
        asset_name: Windows.exe
        tag: Nightly
        overwrite: true
        body: "Windows binary executable."
