name: Build

on:
  push:
    branches: ["stable"]
  pull_request:
    branches: ["stable"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Building on Ubuntu.
    runs-on: ubuntu-latest

    steps:
      - name: Purge Ubuntu
        run: |
          sudo apt purge ufw rsyslog logrotate sysstat python3-problem-report sosreport apport

          sudo systemctl mask systemd-journald.service systemd-journald.socket

      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu,x86_64-unknown-linux-musl
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Build Release
        run: |
          sudo apt update && sudo apt install gcc-aarch64-linux-gnu musl-tools -y

          cargo update

          time cargo l --target x86_64-unknown-linux-gnu
          time cargo l --target aarch64-unknown-linux-gnu
          time cargo l --target x86_64-unknown-linux-musl

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload Linux-Gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-gnu/lto/Img
          asset_name: Linux-Gnu
          tag: Stable
          overwrite: true
          body: "Ubuntu Linux-Gnu binary executable."

      - name: Upload Linux-AArch64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/aarch64-unknown-linux-gnu/lto/Img
          asset_name: Linux-AArch64
          tag: Stable
          overwrite: true
          body: "Ubuntu Linux-AArch64 binary executable."

      - name: Upload Linux-Musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-musl/lto/Img
          asset_name: Linux-Musl
          tag: Stable
          overwrite: true
          body: "Ubuntu Linux-Musl binary executable."

  macOS:
    name: Building on macOS.
    runs-on: macos-14

    steps:
      - name: Disable macos spotlight index
        run: |
          sudo mdutil -a -i off
          sudo mdutil -a -d

      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Build Release
        run: |
          cargo update

          time cargo l --target aarch64-apple-darwin
          time cargo l --target x86_64-apple-darwin
          # time cargo l --target arm64e-apple-darwin

          lipo -create target/aarch64-apple-darwin/lto/Img target/x86_64-apple-darwin/lto/Img -output Img-Universal

          find ./target -iname img -type f | xargs ls -hl
          ls -hl Img-Universal
          sw_vers
          hostinfo
          sysctl -a | grep brand

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload macOS x86-64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-apple-darwin/lto/Img
          asset_name: macOS-x86_64
          tag: Stable
          overwrite: true
          body: "macOS x86-64 binary executable."

      - name: Upload macOS-AArch64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/aarch64-apple-darwin/lto/Img
          asset_name: macOS-AArch64
          tag: Stable
          overwrite: true
          body: "macOS AArch64 binary executable."

      - name: Upload macOS-Universal to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Img-Universal
          asset_name: macOS-Universal
          tag: Stable
          overwrite: true
          body: "macOS Universal binary executable."

  Windows:
    name: Building on Windows.
    runs-on: windows-latest

    steps:
      - name: Disable windows services
        run: |
          sc config "WSearch" start=disabled
          sc config "DiagTrack" start=disabled
          sc config "WdiServiceHost" start=disabled
          sc config "WdiSystemHost" start=disabled
          sc config "PcaSvc" start=disabled
          sc config "WerSvc" start=disabled
          sc stop "DPS"
          sc stop "pla"

          Get-Service -ErrorAction SilentlyContinue|? name -Like "*TELEMETRY*" | Set-Service -StartMode Disabled
          Get-Service -ErrorAction SilentlyContinue|? name -Like "*TELEMETRY*" | ? status -eq "running" | Stop-Service
          Get-Service -ErrorAction SilentlyContinue|? name -Like "*CEIP*" | Set-Service -StartMode Disabled
          Get-Service -ErrorAction SilentlyContinue|? name -Like "*CEIP*" | ? status -eq "running" | Stop-Service
          Get-Service -ErrorAction SilentlyContinue|? name -Like "*Diagnostic*" | Set-Service -StartMode Disabled
          Get-Service -ErrorAction SilentlyContinue|? name -Like "*Diagnostic*" | ? status -eq "running" | Stop-Service

      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-pc-windows-msvc
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Build release
        run: |
          cargo update

          cargo l --target x86_64-pc-windows-msvc
          cargo l --target aarch64-pc-windows-msvc

          cmd /r dir /s target\Img.exe
          systeminfo

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload Windows-x64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-pc-windows-msvc/lto/Img.exe
          asset_name: Windows.exe
          tag: Stable
          overwrite: true
          body: "Windows x64 binary executable."

      - name: Upload Windows-AArch64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/aarch64-pc-windows-msvc/lto/Img.exe
          asset_name: Windows-AArch64.exe
          tag: Stable
          overwrite: true
          body: "Windows AArch64 binary executable."
