name: BSD Unix

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Building for {Free,Open,Net}BSD and Solaris/Illumos.
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Purge Ubuntu
        run: |
          sudo apt purge -y ufw rsyslog logrotate sysstat python3-problem-report sosreport apport
          sudo apt autoremove -y && sudo apt clean
          sudo systemctl disable --now systemd-journald

      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Cross-rs
        run: cargo install cross --git https://github.com/cross-rs/cross --branch main

      - name: Build Release
        run: |
          cargo update
          set +e -x

          # x86_64-unknown-dragonfly,
          # powerpc64-ibm-aix,
          # aarch64-unknown-illumos,

          targets=(
            x86_64-unknown-freebsd
            x86_64-unknown-netbsd
            x86_64-unknown-illumos
            x86_64-unknown-dragonfly
            x86_64-pc-solaris
            sparcv9-sun-solaris
          )

          for target in ${targets[@]}; do
            time cross build -q --config 'build.rustc-wrapper=""' --profile src -Zbuild-std=std,proc_macro,panic_abort -Zbuild-std-features=panic_immediate_abort,optimize_for_size --target $target
          done

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "x86_64-unknown-freebsd Freebsd-x86_64"
                  "x86_64-unknown-netbsd Netbsd-x86_64"
                  "x86_64-unknown-illumos Illumos-x86_64"
                  "x86_64-unknown-dragonfly Dragonfly-x86_64"
                  "x86_64-pc-solaris Solaris-x86_64"
                  "sparcv9-sun-solaris Solaris-sparcv9"
          )
          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/src/Img target/$arch/src/$name || true
            gh release upload Nightly target/$arch/src/$name --clobber || true
          done
