name: BSD Unix

on:
  push:
    branches: ["stable"]
  pull_request:
    branches: ["stable"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Building for {Free,Net,Open}BSD and Solaris/Illumos.
    runs-on: ubuntu-24.04

    steps:
      - name: Purge Ubuntu
        run: |
          sudo apt purge ufw rsyslog logrotate sysstat python3-problem-report sosreport apport
          sudo apt autoremove && sudo apt clean
          sudo systemctl disable --now systemd-journald

      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Cross-rs
        run: |
          wget https://github.com/cross-rs/cross/releases/latest/download/cross-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf cross-x86_64-unknown-linux-gnu.tar.gz
          sudo mv cross /usr/local/bin/

      - name: Build Release
        continue-on-error: true
        run: |
          cargo update
          set +e -x

          targets=(
            x86_64-unknown-freebsd
            x86_64-unknown-netbsd
            x86_64-unknown-illumos
            x86_64-pc-solaris
            sparcv9-sun-solaris
          )

          for target in ${targets[@]}; do
            time cross build -q --config 'build.rustc-wrapper=""' --profile lto --target $target
          done

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "x86_64-unknown-freebsd Freebsd-x86_64"
                  "x86_64-unknown-netbsd Netbsd-x86_64"
                  "x86_64-unknown-illumos Illumos-x86_64"
                  "x86_64-pc-solaris Solaris-x86_64"
                  "sparcv9-sun-solaris Solaris-sparcv9"
          )
          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/lto/Img target/$arch/lto/$name || true
            gh release upload Stable target/$arch/lto/$name --clobber || true
          done
