name: Stable-Cross

on:
  push:
    branches: ["stable"]
  pull_request:
    branches: ["stable"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Building for {Free,Net,Open}BSD and Solaris/Illumos.
    runs-on: ubuntu-24.04

    steps:
      - name: Purge Ubuntu
        run: |
          sudo apt purge ufw rsyslog logrotate sysstat python3-problem-report sosreport apport

          sudo systemctl mask systemd-journald.service systemd-journald.socket

      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Cross-rs
        run: cargo install cross --git https://github.com/cross-rs/cross --branch main

      - name: Build Release
        run: |
          cargo update

          function cb(){
            local target="$1"
            time cross build --config 'build.rustc-wrapper=""' --profile lto --target $target
          }

          cb x86_64-unknown-freebsd
          cb x86_64-unknown-netbsd
          cb x86_64-unknown-illumos
          cb x86_64-pc-solaris
          cb sparcv9-sun-solaris
          cb loongarch64-unknown-linux-gnu
          cb loongarch64-unknown-linux-musl

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Upload Freebsd-x86_64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-freebsd/lto/Img
          asset_name: Freebsd-x86_64
          tag: Stable
          overwrite: true
          body: "Ubuntu Freebsd-x86_64 binary executable."

      - name: Upload Netbsd-x86_64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-netbsd/lto/Img
          asset_name: Netbsd-x86_64
          tag: Stable
          overwrite: true
          body: "Ubuntu Netbsd-x86_64 binary executable."

      - name: Upload Illumos-x86_64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-illumos/lto/Img
          asset_name: Illumos-x86_64
          tag: Stable
          overwrite: true
          body: "Ubuntu Illumos-x86_64 binary executable."

      - name: Upload Solaris-x86_64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-pc-solaris/lto/Img
          asset_name: Solaris-x86_64
          tag: Stable
          overwrite: true
          body: "Ubuntu Solaris-x86_64 binary executable."

      - name: Upload Solaris-sparcv9 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/sparcv9-sun-solaris/lto/Img
          asset_name: Solaris-sparcv9
          tag: Stable
          overwrite: true
          body: "Ubuntu Solaris-sparcv9 binary executable."

      - name: Upload Linux-loongarch64-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/loongarch64-unknown-linux-gnu/lto/Img
          asset_name: Linux-loongarch64-gnu
          tag: Stable
          overwrite: true
          body: "Ubuntu Linux-loongarch64-gnu binary executable."

      - name: Upload Linux-loongarch64-musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/loongarch64-unknown-linux-musl/lto/Img
          asset_name: Linux-loongarch64-musl
          tag: Stable
          overwrite: true
          body: "Ubuntu Linux-loongarch64-musl binary executable."
