name: Linux

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Building on Ubuntu.
    runs-on: ubuntu-latest

    steps:
      - name: Purge Ubuntu
        run: |
          sudo apt purge ufw rsyslog logrotate sysstat python3-problem-report sosreport apport

          sudo systemctl mask systemd-journald.service systemd-journald.socket

      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          # targets: aarch64-unknown-linux-gnu,aarch64-unknown-linux-musl,x86_64-unknown-linux-musl,riscv64gc-unknown-linux-gnu,riscv64gc-unknown-linux-musl,s390x-unknown-linux-gnu
          components: rust-src
          # toolchain: nightly-2024-08-14

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Build Release
        run: |
          sudo apt update && sudo apt install gcc-aarch64-linux-gnu gcc-riscv64-linux-gnu gcc-s390x-linux-gnu gcc-powerpc64-linux-gnu musl-tools -y
          pip install cargo-zigbuild

          cargo update

          # time cargo s powerpc64-ibm-aix
          time cargo s powerpc64-unknown-linux-gnu
          time cargo s powerpc64-unknown-linux-musl

          time cargo s s390x-unknown-linux-gnu
          time cargo s s390x-unknown-linux-musl

          time cargo s riscv64gc-unknown-linux-gnu
          time cargo s riscv64gc-unknown-linux-musl

          time cargo s x86_64-unknown-linux-gnu
          time cargo s x86_64-unknown-linux-musl

          time cargo s aarch64-unknown-linux-gnu
          time cargo s aarch64-unknown-linux-musl

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      # - name: Upload powerpc64-ibm-aix to a GitHub release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: target/powerpc64-ibm-aix/src/Img
      #     asset_name: powerpc64-ibm-aix
      #     tag: Nightly
      #     overwrite: true
      #     body: "Ubuntu powerpc64-ibm-aix binary executable."

      - name: Upload powerpc64-linux-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/powerpc64-unknown-linux-gnu/src/Img
          asset_name: powerpc64-linux-gnu
          tag: Nightly
          overwrite: true
          body: "Ubuntu powerpc64-linux-gnu binary executable."

      - name: Upload powerpc64-linux-musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/powerpc64-unknown-linux-musl/src/Img
          asset_name: powerpc64-linux-musl
          tag: Nightly
          overwrite: true
          body: "Ubuntu powerpc64-linux-musl binary executable."

      - name: Upload Linux-s390x-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/s390x-unknown-linux-gnu/src/Img
          asset_name: Linux-s390x-gnu
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-s390x-gnu binary executable."

      - name: Upload Linux-s390x-musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/s390x-unknown-linux-musl/src/Img
          asset_name: Linux-s390x-musl
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-s390x-musl binary executable."

      - name: Upload Linux-riscv64gc-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/riscv64gc-unknown-linux-gnu/src/Img
          asset_name: Linux-riscv64gc-gnu
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-riscv64gc-gnu binary executable."

      - name: Upload Linux-riscv64gc-musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/riscv64gc-unknown-linux-musl/src/Img
          asset_name: Linux-riscv64gc-musl
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-riscv64gc-musl binary executable."

      - name: Upload Linux-x86_64-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-gnu/src/Img
          asset_name: Linux-x86_64-gnu
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-x86_64-gnu binary executable."

      - name: Upload Linux-x86_64-musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-musl/src/Img
          asset_name: Linux-x86_64-musl
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-x86_64-musl binary executable."

      - name: Upload Linux-aarch64-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/aarch64-unknown-linux-gnu/src/Img
          asset_name: Linux-aarch64-gnu
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-aarch64-gnu binary executable."

      - name: Upload Linux-aarch64-musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/aarch64-unknown-linux-musl/src/Img
          asset_name: Linux-aarch64-musl
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-aarch64-musl binary executable."
