name: Linux

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Ubuntu-24.04
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latest nightly build ID
        id: ver
        run: |
          rust=$(curl -s https://static.rust-lang.org/dist/channel-rust-nightly.toml \
            | sed -n '/^\[pkg.rust\]/,/^\[pkg\./p' \
            | grep '^version' \
            | cut -d'"' -f2)
          echo $rust
          echo "rust=$rust" >> $GITHUB_OUTPUT

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-${{ runner.arch }}-nightly-${{ steps.ver.outputs.rust}}-${{ hashFiles('~/.cargo/bin/*') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-nightly-

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Get latest Android NDK version
        run: |
          latest_ndk=$(curl -fsSL https://developer.android.com/ndk/downloads \
            | sed -n 's/.*Latest Stable Version (\([^)]*\)).*/\1/p')
          echo "NDK_VERSION=$latest_ndk" >> $GITHUB_ENV
          echo "Latest NDK: $latest_ndk"

      - name: Android NDK cache
        uses: actions/cache@v4
        with:
          path: ~/android-ndk-${{ env.NDK_VERSION }}
          key: android-ndk-${{ env.NDK_VERSION }}
          restore-keys: android-ndk-${{ env.NDK_VERSION }}

      - name: Setup OpenHarmony SDK
        uses: openharmony-rs/setup-ohos-sdk@main
        with:
          version: "6.0"

      - name: Cache openwrt
        uses: actions/cache@v4
        with:
          path: /home/runner/openwrt
          key: openwrt-${{ runner.os }}-${{ runner.arch }}-
          restore-keys: openwrt-${{ runner.os }}-${{ runner.arch }}-

      - name: Ubuntu apt update and install
        run: sudo apt install gcc-powerpc64-linux-gnu musl-tools libfuse3-dev -qy

      - name: Build Release
        env:
          REDOX_CONFIG: ${{ github.workspace }}/.config/config.toml
        run: |
          # sudo snap install zig --classic --beta
          # pipx install cargo-zigbuild

          ver=${NDK_VERSION}
          export ANDROID_NDK_HOME=~/android-ndk-$ver
          ln -sf "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64" ndk

          if [ ! -d ~/android-ndk-${ver} ]; then
            mkdir -p ~/android-ndk-${ver}
            echo "Downloading Android NDK..."
            curl -fsSLO https://dl.google.com/android/repository/android-ndk-${ver}-linux.zip
            echo "Unzipping Android NDK..."
            unzip -q android-ndk-${ver}-linux.zip -d ~/
          fi

          ln -sf $OHOS_SDK_NATIVE/llvm ohos
          ln -sf $OHOS_SDK_NATIVE/sysroot ohos-root

          cargo update
          set +e -x

          if [ ! -f ~/.cargo/bin/redoxer ]; then
            cargo install --git https://gitlab.redox-os.org/redox-os/redoxer.git redoxer -q
          fi
          redoxer toolchain

          targets=(
            x86_64-unknown-redox
          )
          for target in ${targets[@]}; do
            time redoxer build -- -q --profile redox -Zbuild-std=std,proc_macro,panic_abort -Zbuild-std-features=optimize_for_size --target $target
          done

          if [ ! -d /home/runner/openwrt ]; then
            mkdir -p /home/runner/openwrt
            curl -LsSf https://downloads.openwrt.org/releases/24.10.5/targets/octeon/generic/openwrt-toolchain-24.10.5-octeon-generic_gcc-13.3.0_musl.Linux-x86_64.tar.zst | tar --zstd -xf - -C /home/runner/openwrt
          fi

          ln -sf /home/runner/openwrt/openwrt-toolchain-24.10.5-octeon-generic_gcc-13.3.0_musl.Linux-x86_64/toolchain-mips64_octeonplus_64_gcc-13.3.0_musl wrt

          targets=(
            mips64-openwrt-linux-musl
            aarch64-unknown-linux-ohos
            armv7-unknown-linux-ohos
            x86_64-unknown-linux-ohos
            riscv64-linux-android
            aarch64-linux-android
            armv7-linux-androideabi
            thumbv7neon-linux-androideabi
            x86_64-linux-android
            powerpc64-unknown-linux-gnu
            ./powerpc64-unknown-linux-musl-elfv1.json
            powerpc64-unknown-linux-musl
          )

          for target in ${targets[@]}; do
            time cargo s $target
          done

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "riscv64-linux-android Android-riscv64"
                  "aarch64-linux-android Android-aarch64"
                  "armv7-linux-androideabi Android-armv7"
                  "thumbv7neon-linux-androideabi Android-thumbv7neon"
                  "x86_64-linux-android Android-x86_64"
                  "powerpc64-unknown-linux-gnu Linux-powerpc64-gnu"
                  "powerpc64-unknown-linux-musl Linux-powerpc64-musl"
                  "powerpc64-unknown-linux-musl-elfv1 Linux-powerpc64-musl"
                  "aarch64-unknown-linux-ohos Android-aarch64-ohos"
                  "armv7-unknown-linux-ohos Android-armv7-ohos"
                  "x86_64-unknown-linux-ohos Android-x86_64-ohos"
                  "x86_64-unknown-hermit Hermit-x86_64"
                  "riscv64gc-unknown-hermit Hermit-riscv64gc"
                  "aarch64-unknown-hermit Hermit-aarch64"
                  "mips64-openwrt-linux-musl Openwrt-mips64-musl"
          )
          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/src/Img target/$arch/src/$name || true
            gh release upload Nightly target/$arch/src/$name --clobber || true
          done

          targets=("x86_64-unknown-redox Redox-x86_64")
          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/redox/Img target/$arch/redox/$name || true
            gh release upload Nightly target/$arch/redox/$name --clobber || true
          done
