name: Linux

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Building on Ubuntu.
    runs-on: ubuntu-latest

    steps:
      - name: Purge Ubuntu
        run: |
          sudo apt purge ufw rsyslog logrotate sysstat python3-problem-report sosreport apport

          sudo systemctl mask systemd-journald.service systemd-journald.socket

      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Build Release
        run: |
          # wget -qO- https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/ubuntu/dists/jammy/615d762f.gpg.key | sudo tee /etc/apt/trusted.gpg.d/615d762f.asc

          # echo "deb [signed-by=/etc/apt/trusted.gpg.d/615d762f.asc] https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/ubuntu jammy at17.0" | sudo tee -a /etc/apt/sources.list

          sudo apt update && sudo apt upgrade && sudo apt install gcc-aarch64-linux-gnu gcc-riscv64-linux-gnu gcc-s390x-linux-gnu gcc-powerpc64-linux-gnu gcc-sparc64-linux-gnu gcc-mips64-linux-gnuabi64 musl-tools -y
          # advance-toolchain-at17.0-cross-ppc64le
          pip install cargo-zigbuild

          cargo update

          time cargo s x86_64-pc-solaris
          time cargo s mips64-unknown-linux-gnuabi64
          time cargo s mips64-unknown-linux-muslabi64

          time cargo s sparc64-unknown-linux-gnu
          # time cargo s sparcv9-sun-solaris

          # time cargo s powerpc64-ibm-aix
          time cargo z powerpc64-unknown-linux-gnu
          time cargo z powerpc64-unknown-linux-musl

          time cargo s s390x-unknown-linux-gnu
          time cargo s s390x-unknown-linux-musl

          time cargo s riscv64gc-unknown-linux-gnu
          time cargo s riscv64gc-unknown-linux-musl

          time cargo s x86_64-unknown-linux-gnu
          time cargo s x86_64-unknown-linux-musl

          time cargo s aarch64-unknown-linux-gnu
          time cargo s aarch64-unknown-linux-musl

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload Linux-mips64-gnuabi64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/mips64-unknown-linux-gnuabi64/src/Img
          asset_name: Linux-mips64-gnuabi64
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-mips64-gnuabi64 binary executable."

      - name: Upload Linux-mips64-muslabi64 to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/mips64-unknown-linux-muslabi64/src/Img
          asset_name: Linux-mips64-muslabi64
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-mips64-muslabi64 binary executable."

      - name: Upload Linux-sparc64-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/sparc64-unknown-linux-gnu/src/Img
          asset_name: Linux-sparc64-gnu
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-sparc64-gnu binary executable."

      # - name: Upload Solaris-sparcv9 to a GitHub release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: target/sparcv9-sun-solaris/src/Img
      #     asset_name: Solaris-sparcv9
      #     tag: Nightly
      #     overwrite: true
      #     body: "Ubuntu Solaris-sparcv9 binary executable."

      - name: Upload powerpc64-linux-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/powerpc64-unknown-linux-gnu/src/Img
          asset_name: Linux-powerpc64-gnu
          tag: Nightly
          overwrite: true
          body: "Ubuntu powerpc64-linux-gnu binary executable."

      - name: Upload powerpc64-linux-musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/powerpc64-unknown-linux-musl/src/Img
          asset_name: Linux-powerpc64-musl
          tag: Nightly
          overwrite: true
          body: "Ubuntu powerpc64-linux-musl binary executable."

      - name: Upload Linux-s390x-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/s390x-unknown-linux-gnu/src/Img
          asset_name: Linux-s390x-gnu
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-s390x-gnu binary executable."

      - name: Upload Linux-s390x-musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/s390x-unknown-linux-musl/src/Img
          asset_name: Linux-s390x-musl
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-s390x-musl binary executable."

      - name: Upload Linux-riscv64gc-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/riscv64gc-unknown-linux-gnu/src/Img
          asset_name: Linux-riscv64gc-gnu
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-riscv64gc-gnu binary executable."

      - name: Upload Linux-riscv64gc-musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/riscv64gc-unknown-linux-musl/src/Img
          asset_name: Linux-riscv64gc-musl
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-riscv64gc-musl binary executable."

      - name: Upload Linux-x86_64-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-gnu/src/Img
          asset_name: Linux-x86_64-gnu
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-x86_64-gnu binary executable."

      - name: Upload Linux-x86_64-musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-musl/src/Img
          asset_name: Linux-x86_64-musl
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-x86_64-musl binary executable."

      - name: Upload Linux-aarch64-gnu to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/aarch64-unknown-linux-gnu/src/Img
          asset_name: Linux-aarch64-gnu
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-aarch64-gnu binary executable."

      - name: Upload Linux-aarch64-musl to a GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/aarch64-unknown-linux-musl/src/Img
          asset_name: Linux-aarch64-musl
          tag: Nightly
          overwrite: true
          body: "Ubuntu Linux-aarch64-musl binary executable."
