name: Linux

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Ubuntu-24.04
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Ubuntu apt update and install
        run: |
          # wget https://apt.llvm.org/llvm-snapshot.gpg.key
          # sudo apt-key add llvm-snapshot.gpg.key

          # sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc)-21 main"

          sudo apt update -q && sudo apt install pipx gcc-powerpc64-linux-gnu musl-tools qemu-user-static -qy

      - name: Build Release
        run: |
          sudo snap install zig --classic --beta
          pipx install cargo-zigbuild

          cargo update
          set +e -x
          abi=$(powerpc64-linux-gnu-gcc -v 2>&1 | grep ABI)
          echo $abi
          targets=(
            powerpc64-unknown-linux-gnu
            powerpc64-unknown-linux-musl
          )

          zigs=(
            powerpc64-unknown-linux-musl
          )

          for target in ${targets[@]}; do
            time cargo s --target $target
          done

          for zig in ${zigs[@]}; do
            time cargo z $zig
          done

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "powerpc64-unknown-linux-gnu Linux-powerpc64-gnu"
                  "powerpc64-unknown-linux-musl Linux-powerpc64-musl"
          )
          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/src/Img target/$arch/src/$name || true
            gh release upload Nightly target/$arch/src/$name --clobber || true
          done
