name: Linux-arm

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Building on Ubuntu.
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Purge Ubuntu
        run: |
          sudo apt purge -y ufw rsyslog logrotate sysstat python3-problem-report sosreport apport
          sudo apt autoremove -y && sudo apt clean
          sudo systemctl disable --now systemd-journald

      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Ubuntu apt update and install
        run: |
          sudo apt update -q && sudo apt install -q gcc-x86-64-linux-gnu gcc-riscv64-linux-gnu gcc-s390x-linux-gnu gcc-powerpc64le-linux-gnu  gcc-sparc64-linux-gnu gcc-mips64-linux-gnuabi64 gcc-mips64el-linux-gnuabi64 gcc-14-loongarch64-linux-gnu musl-tools -y

      - name: Build Release
        run: |
          # sudo snap install zig --classic --beta
          # pipx install cargo-zigbuild

          cargo update
          set +e -x

          targets=(
            powerpc64le-unknown-linux-gnu
            powerpc64le-unknown-linux-musl
            riscv64gc-unknown-linux-gnu
            riscv64gc-unknown-linux-musl
            x86_64-unknown-linux-gnu
            x86_64-unknown-linux-musl
            aarch64-unknown-linux-gnu
            sparc64-unknown-linux-gnu
            mips64-unknown-linux-gnuabi64
            mips64-unknown-linux-muslabi64
            mips64el-unknown-linux-gnuabi64
            mips64el-unknown-linux-muslabi64
            s390x-unknown-linux-gnu
            s390x-unknown-linux-musl
            aarch64-unknown-linux-musl
            loongarch64-unknown-linux-gnu
            loongarch64-unknown-linux-musl
          )
          # powerpc64-unknown-linux-gnu,
          # powerpc64-unknown-linux-musl,
          for target in ${targets[@]}; do
            time cargo s --target $target
          done

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "powerpc64le-unknown-linux-gnu Linux-powerpc64le-gnu"
                  "powerpc64le-unknown-linux-musl Linux-powerpc64le-musl"
                  "riscv64gc-unknown-linux-gnu Linux-riscv64gc-gnu"
                  "riscv64gc-unknown-linux-musl Linux-riscv64gc-musl"
                  "x86_64-unknown-linux-gnu Linux-x86_64-gnu"
                  "x86_64-unknown-linux-musl Linux-x86_64-musl"
                  "aarch64-unknown-linux-gnu Linux-aarch64-gnu"
                  "aarch64-unknown-linux-musl Linux-aarch64-musl"
                  "sparc64-unknown-linux-gnu Linux-sparc64-gnu"
                  "mips64-unknown-linux-gnuabi64 Linux-mips64-gnuabi64"
                  "mips64-unknown-linux-muslabi64 Linux-mips64-muslabi64"
                  "mips64el-unknown-linux-gnuabi64 Linux-mips64el-gnuabi64"
                  "mips64el-unknown-linux-muslabi64 Linux-mips64el-muslabi64"
                  "s390x-unknown-linux-gnu Linux-s390x-gnu"
                  "s390x-unknown-linux-musl Linux-s390x-musl"
                  "loongarch64-unknown-linux-gnu Linux-loongarch64-gnu"
                  "loongarch64-unknown-linux-musl Linux-loongarch64-musl"
          )
          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/src/Img target/$arch/src/$name || true
            gh release upload Nightly target/$arch/src/$name --clobber || true
          done
