name: Linux-arm

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Ubuntu-24.04-arm
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Ubuntu apt update and install
        run: |
          sudo apt install -q gcc-x86-64-linux-gnu gcc-riscv64-linux-gnu gcc-s390x-linux-gnu gcc-powerpc64le-linux-gnu  gcc-sparc64-linux-gnu gcc-mips64-linux-gnuabi64 gcc-mips64el-linux-gnuabi64 gcc-14-loongarch64-linux-gnu gcc-mipsisa64r6el-linux-gnuabi64 gcc-mipsisa64r6-linux-gnuabi64 gcc-arm-linux-gnueabihf musl-tools -y

      - name: Build Release
        run: |
          # sudo snap install zig --classic --beta
          # pipx install cargo-zigbuild

          cargo update
          set +e -x

          targets=(
            thumbv7neon-unknown-linux-gnueabihf
            thumbv7neon-unknown-linux-musleabihf
            powerpc64le-unknown-linux-gnu
            powerpc64le-unknown-linux-musl
            riscv64gc-unknown-linux-gnu
            riscv64gc-unknown-linux-musl
            riscv64a23-unknown-linux-gnu
            x86_64-unknown-linux-gnu
            x86_64-unknown-linux-musl
            aarch64-unknown-linux-gnu
            aarch64-unknown-linux-musl
            sparc64-unknown-linux-gnu
            mips64-unknown-linux-gnuabi64
            mips64-unknown-linux-muslabi64
            mips64el-unknown-linux-gnuabi64
            mips64el-unknown-linux-muslabi64
            mipsisa64r6-unknown-linux-gnuabi64
            mipsisa64r6el-unknown-linux-gnuabi64
            s390x-unknown-linux-gnu
            s390x-unknown-linux-musl
            loongarch64-unknown-linux-gnu
            loongarch64-unknown-linux-musl
          )
          # powerpc64-unknown-linux-gnu,
          # powerpc64-unknown-linux-musl,
          for target in ${targets[@]}; do
            time cargo s $target
          done

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
            thumbv7neon-unknown-linux-gnueabihf
            thumbv7neon-unknown-linux-musleabihf
            powerpc64le-unknown-linux-gnu
            powerpc64le-unknown-linux-musl
            riscv64gc-unknown-linux-gnu
            riscv64gc-unknown-linux-musl
            riscv64a23-unknown-linux-gnu
            x86_64-unknown-linux-gnu
            x86_64-unknown-linux-musl
            aarch64-unknown-linux-gnu
            aarch64-unknown-linux-musl
            sparc64-unknown-linux-gnu
            mips64-unknown-linux-gnuabi64
            mips64-unknown-linux-muslabi64
            mips64el-unknown-linux-gnuabi64
            mips64el-unknown-linux-muslabi64
            mipsisa64r6-unknown-linux-gnuabi64
            mipsisa64r6el-unknown-linux-gnuabi64
            s390x-unknown-linux-gnu
            s390x-unknown-linux-musl
            loongarch64-unknown-linux-gnu
            loongarch64-unknown-linux-musl
          )
          for target in "${targets[@]}"; do
            IFS='-' read -r arch vendor os rest <<< "$target"
            os_cap="${os^}"
            if [[ -n "$rest" ]]; then
                name="${os_cap}-${arch}-${rest}"
            else
                name="${os_cap}-${arch}"
            fi
            echo "Uploading $name..."
            mv target/$target/src/Img target/$target/src/$name || true
            gh release upload Nightly --clobber target/$target/src/$name || true
          done
