name: macOS

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  macOS:
    name: macOS-15
    runs-on: macos-15

    steps:
      - name: Disable macos spotlight index
        run: |
          sudo mdutil -a -i off
          sudo mdutil -a -d
          sudo pmset -a powernap 0
          sudo pmset -a sleep 0

      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latest nightly build ID
        id: ver
        run: |
          rust=$(curl -s https://static.rust-lang.org/dist/channel-rust-nightly.toml \
            | sed -n '/^\[pkg.rust\]/,/^\[pkg\./p' \
            | grep '^version' \
            | cut -d'"' -f2)
          echo $rust
          echo "rust=$rust" >> $GITHUB_OUTPUT

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-${{ runner.arch }}-nightly-${{ steps.ver.outputs.rust}}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-nightly-

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-wasip2
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Cache llvm-mingw
        uses: actions/cache@v4
        with:
          path: llvm-mingw
          key: ${{ runner.os }}-llvm-mingw-${{ hashFiles('llvm-mingw/**') }}
          restore-keys: ${{ runner.os }}-llvm-mingw-

      - name: Build Release
        run: |
          cargo update
          set +e -x

          if [ ! -d llvm-mingw ]; then
            mkdir llvm-mingw
            curl -LsSf https://github.com/mstorsjo/llvm-mingw/releases/download/20251216/llvm-mingw-20251216-ucrt-macos-universal.tar.xz | tar -xJf - -C llvm-mingw --strip-components=1
          fi
          export PATH=$PWD/llvm-mingw/bin:$PATH

          targets=(
            aarch64-pc-windows-gnullvm
            x86_64-pc-windows-gnullvm
            aarch64-apple-ios
            arm64e-apple-ios
            aarch64-apple-tvos
            arm64e-apple-tvos
            aarch64-apple-watchos
            aarch64-apple-visionos
            aarch64-apple-darwin
            arm64e-apple-darwin
            x86_64h-apple-darwin
            wasm32-wasip2
          )

          for target in ${targets[@]}; do
            time cargo s $target
          done

          lipo -create target/arm64e-apple-darwin/src/Img target/x86_64h-apple-darwin/src/Img -output Img-Universal

          find ./target \( -iname img -o -iname img.exe -o -iname img.wasm -o -iname Img-Universal \) -type f | xargs ls -hl
          sw_vers
          hostinfo
          sysctl -a | grep brand

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "x86_64h-apple-darwin Apple-macOS-x86_64h"
                  "aarch64-apple-darwin Apple-macOS-aarch64"
                  "arm64e-apple-darwin Apple-macOS-arm64e"
                  "aarch64-apple-ios Apple-iOS-aarch64"
                  "arm64e-apple-ios Apple-iOS-arm64e"
                  "aarch64-apple-tvos Apple-tvOS-aarch64"
                  "arm64e-apple-tvos Apple-tvOS-arm64e"
                  "aarch64-apple-watchos Apple-watchOS-aarch64"
                  "aarch64-apple-visionos Apple-visionOS-aarch64"
                  "aarch64-pc-windows-gnullvm Windows-aarch64-gnullvm.exe",
                  "x86_64-pc-windows-gnullvm Windows-x86_64-gnullvm.exe",
                  "wasm32-wasip2 wasm32-wasip2.wasm",
          )

          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            for f in Img Img.exe Img.wasm; do
                if [ -e "target/$arch/src/$f" ]; then
                    mv "target/$arch/src/$f" "target/$arch/src/$name"
                    break
                fi
            done
            gh release upload Nightly target/$arch/src/$name --clobber || true
          done

          echo "Uploading Apple-macOS-universal..."
          gh release upload Nightly Img-Universal#Apple-macOS-universal --clobber || true
