name: macOS

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  macOS:
    name: Building on macOS.
    runs-on: macos-15
    strategy:
      matrix:
        target:
          - {
              arch: "x86_64h-apple-darwin",
              name: "Apple-macOS-x86_64h",
              desc: "macOS x86-64h",
            }
          - {
              arch: "aarch64-apple-darwin",
              name: "Apple-macOS-aarch64",
              desc: "macOS aarch64",
            }
          - {
              arch: "aarch64-apple-ios",
              name: "iOS-aarch64",
              desc: "iOS aarch64",
            }
          - {
              arch: "aarch64-apple-tvos",
              name: "tvOS-aarch64",
              desc: "tvOS aarch64",
            }
          - {
              arch: "aarch64-apple-visionos",
              name: "visionos-aarch64",
              desc: "visionos aarch64",
            }
          - {
              arch: "aarch64-apple-watchos",
              name: "watchos-aarch64",
              desc: "watchosaarch64",
            }
          - {
              arch: "wasm32-wasip2",
              name: "wasm32-wasip2.wasm",
              desc: "Wasm32-wasip2",
            }

    steps:
      - name: Disable macos spotlight index
        run: |
          sudo mdutil -a -i off
          sudo mdutil -a -d
          sudo pmset -a powernap 0
          sudo pmset -a sleep 0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          target: wasm32-wasip2
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Build Release
        run: |
          cargo update
          set +e -x

          targets=(
            aarch64-apple-ios,
            aarch64-apple-tvos,
            aarch64-apple-watchos,
            aarch64-apple-visionos,
            aarch64-apple-darwin,
            x86_64h-apple-darwin,
            wasm32-wasip2,
          )

          for target in "${targets[@]}"; do
            echo "Building for target: $target"
            time cargo s --target $target
          done

          lipo -create target/arm64e-apple-darwin/src/Img target/x86_64h-apple-darwin/src/Img -output Img-Universal

          find . \( -iname img -o -iname img.wasm -o -iname Img-Universal \) -type f | xargs ls -hl
          sw_vers
          hostinfo
          sysctl -a | grep brand

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload ${{ matrix.target.name }} to a GitHub release
        uses: svenstaro/upload-release-action@v2
        continue-on-error: true
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target.arch }}/src/Img
          asset_name: ${{ matrix.target.name }}
          tag: Nightly
          overwrite: true
          body: ${{ matrix.target.desc }} binary executable.

      - name: Upload macOS-universal to a GitHub release
        uses: svenstaro/upload-release-action@v2
        continue-on-error: true
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Img-Universal
          asset_name: Apple-macOS-universal
          tag: Nightly
          overwrite: true
          body: "macOS universal binary executable."
