name: Solaris+Fuchsia

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Solaris+Fuchsia
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get latest nightly build ID
        id: ver
        run: |
          rust=$(curl -s https://static.rust-lang.org/dist/channel-rust-nightly.toml \
            | sed -n '/^\[pkg.rust\]/,/^\[pkg\./p' \
            | grep '^version' \
            | cut -d'"' -f2)
          echo $rust
          echo "rust=$rust" >> $GITHUB_OUTPUT

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-${{ runner.arch }}-nightly-${{ steps.ver.outputs.rust}}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-nightly-

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Cross-rs
        run: |
          wget https://github.com/cross-rs/cross/releases/latest/download/cross-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf cross-x86_64-unknown-linux-gnu.tar.gz
          sudo mv cross /usr/local/bin/

      # - name: Ubuntu apt update and install
      # run: sudo apt install -y zfsutils-linux

      # - name: Cache Illumos/Solaris
      #   uses: actions/cache@v4
      #   with:
      #     path: /home/runner/Illumos
      #     key: Illomos-${{ runner.os }}-${{ runner.arch }}
      #     restore-keys: Illomos-${{ runner.os }}-${{ runner.arch }}

      - name: Build Release
        run: |
          cargo update
          set +e -x

          # ln -sfn /home/runner/Illumos Illumos

          # if [ ! -f Illumos/omnios-r151056.zfs ]; then
          #   curl -fsSL https://downloads.omnios.org/media/stable/omnios-r151056.zfs.xz | xz -d > Illumos/omnios-r151056.zfs
          #   mkdir -p Illumos/omnios
          # fi

          # sudo truncate -s 1G /tmp/omnios.img
          # sudo zpool create -f solaris /tmp/omnios.img
          # sudo zfs recv -o mountpoint=/home/runner/Illumos/omnios solaris/omnios < Illumos/omnios-r151056.zfs

          # zpool status
          # zfs list

          if [ ! -d /home/runner/Fuchsia ]; then
            curl -LsSf 'https://chrome-infra-packages.appspot.com/client?platform=linux-amd64&version=latest' -o cipd
            chmod +x cipd
            sudo mv cipd /usr/local/bin/
            mkdir -p /home/runner/Fuchsia
            cipd install fuchsia/sdk/core/linux-amd64 latest -root /home/runner/Fuchsia
          fi

          ln -sfn /home/runner/Fuchsia fuchsia
          ls -ahl fuchsia/bin/*
          ls -ahl fuchsia
          targets=(
            aarch64-unknown-fuchsia
            riscv64gc-unknown-fuchsia
            x86_64-unknown-fuchsia
          )
          for target in ${targets[@]}; do
            time cargo s $target
          done

          targets=(
            x86_64-unknown-illumos
            x86_64-pc-solaris
            sparcv9-sun-solaris
          )

          for target in ${targets[@]}; do
            # time cargo s $target
            time cross build -q --config 'build.rustc-wrapper=""' --profile src -Zbuild-std=std,proc_macro,panic_abort -Zbuild-std-features=optimize_for_size --target $target
          done

          # sudo zfs destroy -r solaris/omnios
          # sudo zpool destroy solaris

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
            "x86_64-unknown-illumos Illumos-x86_64"
            "x86_64-pc-solaris Solaris-x86_64"
            "sparcv9-sun-solaris Solaris-sparcv9"
          )
          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/src/Img target/$arch/src/$name || true
            gh release upload Nightly target/$arch/src/$name --clobber || true
          done
