name: Sparc64

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Sparc64
    runs-on: ubuntu-26.04

    permissions:
          contents: read
          packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
          # toolchain: nightly-2026-02-09

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Install LLVM
        run: |
          ver=23
          if [ "$ver" = "23" ]; then
              wget https://apt.llvm.org/llvm.sh
              chmod +x llvm.sh
              sudo ./llvm.sh $ver
          fi
          for x in clang clang++ lld; do
            sudo update-alternatives --install "/usr/bin/$x" "$x" "/usr/bin/$x-$ver" 200
          done
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/lld-$ver 200

      # - uses: taiki-e/setup-cross-toolchain-action@v1
      #   with:
      #     target: sparc64-unknown-netbsd@10

      # - uses: taiki-e/setup-cross-toolchain-action@v1
      #   with:
      #     target: sparc64-unknown-openbsd

      - name: Checkout rust-cross-toolchain
        uses: actions/checkout@v7
        with:
          repository: taiki-e/rust-cross-toolchain
          path: rust-cross-toolchain

      - name: Login to GHCR
        run: |
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin

      # - name: Build toolchain
      #   working-directory: rust-cross-toolchain
      #   env:
      #     IMAGE: ghcr.io/${{ github.repository }}
      #     NETBSD_VERSION: "11.0"
      #     OPENBSD_VERSION: "7.9"
      #   run: |
      #     sed -i 's/\[1-8\]\.\*) ext=tgz ;;/[1-9].*|1[0-9].*) ext=tgz ;;/g' \
      #       docker/base/netbsd.Dockerfile

      #     sed -i '/RUN \/test\/test.sh/d' docker/netbsd.Dockerfile
      #     sed -i '/RUN \/test\/test.sh/d' docker/openbsd.Dockerfile

      #     IMAGE="${IMAGE,,}"

      #     # NetBSD base image required by docker/netbsd.Dockerfile
      #     docker buildx build \
      #       --platform linux/amd64 \
      #       --provenance=false \
      #       --load \
      #       --file docker/base/netbsd.Dockerfile \
      #       --build-arg RUST_TARGET=sparc64-unknown-netbsd \
      #       --build-arg HOST_ARCH=amd64 \
      #       --build-arg NETBSD_VERSION="$NETBSD_VERSION" \
      #       --tag ghcr.io/taiki-e/rust-cross-toolchain:sparc64-unknown-netbsd${NETBSD_VERSION}-base-dev-amd64 \
      #       docker/base

      #     # NetBSD final image
      #     docker buildx build \
      #       --platform linux/amd64 \
      #       --provenance=false \
      #       --load \
      #       --file docker/netbsd.Dockerfile \
      #       --build-arg RUST_TARGET=sparc64-unknown-netbsd \
      #       --build-arg HOST_ARCH=amd64 \
      #       --build-arg NETBSD_VERSION="$NETBSD_VERSION" \
      #       --tag "$IMAGE:sparc64-unknown-netbsd11.0" \
      #       docker

      #     # OpenBSD final image
      #     docker buildx build \
      #       --platform linux/amd64 \
      #       --provenance=false \
      #       --load \
      #       --file docker/openbsd.Dockerfile \
      #       --build-arg RUST_TARGET=sparc64-unknown-openbsd \
      #       --build-arg HOST_ARCH=amd64 \
      #       --build-arg OPENBSD_VERSION="$OPENBSD_VERSION" \
      #       --tag "$IMAGE:sparc64-unknown-openbsd7.9" \
      #       docker

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish toolchains
      #   env:
      #     IMAGE: ghcr.io/${{ github.repository }}
      #   run: |
      #     IMAGE="${IMAGE,,}"
      #     docker push "$IMAGE:sparc64-unknown-netbsd11.0"
      #     docker push "$IMAGE:sparc64-unknown-openbsd7.9"

      - name: Cross-rs
        run: |
          # cargo install cross --git https://github.com/cross-rs/cross --branch main -q
          if [ ! -f ~/.cargo/bin/cross ]; then
            wget -qO- https://github.com/cross-rs/cross/releases/latest/download/cross-x86_64-unknown-linux-gnu.tar.gz | tar -xz
            sudo mv cross ~/.cargo/bin/
          fi
          cross --version

      - name: Build Release
        env:
          IMAGE: ghcr.io/${{ github.repository }}
        run: |
          cargo update
          set +e -x

          IMAGE="${IMAGE,,}"
          docker pull "$IMAGE:sparc64-unknown-netbsd11.0"
          docker pull "$IMAGE:sparc64-unknown-openbsd7.9"

          targets=(
            sparc64-unknown-netbsd
            sparc64-unknown-openbsd
          )

          for target in ${targets[@]}; do
            time cargo s $target
            time cross build -q --profile src -Zbuild-std=std,panic_abort --target $target
          done

          # time docker run --rm \
          #       -v "$PWD:/src" \
          #       -w /src \
          #       "$IMAGE:sparc64-unknown-netbsd11.0" \
          #       cargo s sparc64-unknown-netbsd
          # time docker run --rm \
          #       -v "$PWD:/src" \
          #       -w /src \
          #       "$IMAGE:sparc64-unknown-openbsd7.9" \
          #       cargo s sparc64-unknown-openbsd

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
            sparc64-unknown-netbsd
            sparc64-unknown-openbsd
          )
          for target in "${targets[@]}"; do
            IFS='-' read -r arch vendor os abi <<< "$target"
            if [[ -n "$abi" ]]; then
                name="${os^}-${arch}-${abi}"
            else
                name="${os^}-${arch}"
            fi
            echo "Uploading $name..."
            mv target/$target/src/{img,$name} || true
            gh release upload Nightly --clobber target/$target/src/$name || true
          done
