name: Unix

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Unix
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
          # toolchain: nightly-2026-02-09

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Cache sysroot
        uses: actions/cache@v5
        with:
          path: /home/runner/unix
          key: Unix
          restore-keys: Unix

      - name: Install LLVM
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" -- 22
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-22 200
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-22 200
          sudo update-alternatives --install /usr/bin/lld lld /usr/bin/lld-22 200

      - name: Build Release
        run: |
          cargo update
          set +e -x

          mkdir -p /home/runner/unix;
          ln -sf /home/runner/unix sysroot

          freebsd=(amd64 arm64 riscv)
          for arch in "${freebsd[@]}"; do
            if [ ! -d sysroot/freebsd/$arch ]; then
                mkdir -p sysroot/freebsd/$arch
                curl -fsSL https://download.freebsd.org/ftp/releases/$arch/15.1-RELEASE/base.txz \
            | tar -xJf - -C sysroot/freebsd/$arch 2>/dev/null &
            fi
          done

          ppc=(powerpc64 powerpc64le)
          for arch in "${ppc[@]}"; do
            if [ ! -d sysroot/freebsd/$arch ]; then
              mkdir -p sysroot/freebsd/$arch
              curl -fsSL https://download.freebsd.org/ftp/releases/powerpc/$arch/15.1-RELEASE/base.txz \
                | tar -xJf - -C sysroot/freebsd/$arch 2>/dev/null &
            fi
          done

          openbsd=(amd64 arm64 riscv64 powerpc64)
          files=(base79 comp79)
          for arch in "${openbsd[@]}"; do
            if [ ! -d sysroot/openbsd/$arch ]; then
              mkdir -p sysroot/openbsd/$arch
              for file in "${files[@]}"; do
                curl -fsSL https://cdn.openbsd.org/pub/OpenBSD/7.9/$arch/$file.tgz | tar -xzf - -C sysroot/openbsd/$arch 2>/dev/null &
              done
            fi
          done

          netbsd=(amd64 evbarm-aarch64 evbarm-aarch64eb riscv-riscv64)
          files=(base comp etc)
          for arch in "${netbsd[@]}"; do
            if [ ! -d sysroot/netbsd/$arch ]; then
              mkdir -p sysroot/netbsd/$arch
              for file in "${files[@]}"; do
                for ext in tar.xz tgz; do
                        url="https://cdn.netbsd.org/pub/NetBSD/NetBSD-11.0_RC5/$arch/binary/sets/$file.$ext"
                        out="sysroot/netbsd/$arch"
                        if curl -fsSI "$url" &>/dev/null; then
                            echo "→ Fetching $file.$ext"
                            if [ "$ext" = "tar.xz" ]; then
                                curl -fsSL "$url" | tar -xJf - -C "$out" 2>/dev/null &
                            else
                                curl -fsSL "$url" | tar -xzf - -C "$out" 2>/dev/null &
                            fi
                        fi
                    done
              done
            fi
          done

          if [ ! -f sysroot/dfly-x86_64-6.4.2_REL.iso ]; then
            curl -fsSL https://mirror-master.dragonflybsd.org/iso-images/dfly-x86_64-6.4.2_REL.iso.bz2 | bunzip2 -c > sysroot/dfly-x86_64-6.4.2_REL.iso &
            mkdir -p sysroot/dfly
          fi

          wait
          chmod -R u+rwX sysroot

          sudo mount -o loop sysroot/dfly-x86_64-6.4.2_REL.iso sysroot/dfly

          targets=(
            x86_64-unknown-dragonfly
            x86_64-unknown-freebsd
            aarch64-unknown-freebsd
            riscv64gc-unknown-freebsd
            powerpc64-unknown-freebsd
            powerpc64le-unknown-freebsd
            x86_64-unknown-openbsd
            aarch64-unknown-openbsd
            riscv64gc-unknown-openbsd
            powerpc64-unknown-openbsd
            x86_64-unknown-netbsd
            aarch64-unknown-netbsd
            aarch64_be-unknown-netbsd
            riscv64gc-unknown-netbsd
          )

          for target in ${targets[@]}; do
            time cargo s $target
          done

          sudo umount sysroot/dfly

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
            x86_64-unknown-dragonfly
            x86_64-unknown-freebsd
            aarch64-unknown-freebsd
            riscv64gc-unknown-freebsd
            powerpc64-unknown-freebsd
            powerpc64le-unknown-freebsd
            x86_64-unknown-openbsd
            aarch64-unknown-openbsd
            riscv64gc-unknown-openbsd
            powerpc64-unknown-openbsd
            x86_64-unknown-netbsd
            aarch64-unknown-netbsd
            aarch64_be-unknown-netbsd
            riscv64gc-unknown-netbsd
          )
          for target in "${targets[@]}"; do
            IFS='-' read -r arch vendor os abi <<< "$target"
            if [[ -n "$abi" ]]; then
                name="${os^}-${arch}-${abi}"
            else
                name="${os^}-${arch}"
            fi
            echo "Uploading $name..."
            mv target/$target/src/{img,$name} || true
            gh release upload Nightly --clobber target/$target/src/$name || true
          done
