name: Unix

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"

jobs:
  Linux:
    name: Unix
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set cache key date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/git
          key: rust-${{ runner.os }}-nightly-${{ env.DATE }}
          restore-keys: |
            rust-${{ runner.os }}-nightly-

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      # - name: Prepare sysroot dir
      #   run: mkdir -p /home/runner/sysroots

      - name: Cache sysroot
        uses: actions/cache@v4
        id: sysroot-cache
        with:
          path: /home/runner/sysroots
          key: sr-${{ runner.os }}-${{ hashFiles('scripts/sysroot-files.txt') }}
          restore-keys: |
            sr-${{ runner.os }}-

      - name: Ubuntu apt update and install
        run: sudo apt update && sudo apt install -y zfsutils-linux

      - name: Build Release
        run: |
          cargo update
          set +e -x

          SYSROOT="/home/runner/sysroots"
          ln -sfn "$SYSROOT" sysroot

          freebsd=(amd64 arm64 riscv)
          for arch in "${freebsd[@]}"; do
            if [ ! -d $SYSROOT/freebsd/$arch ]; then
                mkdir -p $SYSROOT/freebsd/$arch
                curl -fsSL https://download.freebsd.org/ftp/releases/$arch/14.3-RELEASE/base.txz \
            | tar -xJf - -C $SYSROOT/freebsd/$arch 2>/dev/null &
            fi
          done

          ppc=(powerpc64 powerpc64le)
          for arch in "${ppc[@]}"; do
            if [ ! -d $SYSROOT/freebsd/$arch ]; then
              mkdir -p $SYSROOT/freebsd/$arch
              curl -fsSL https://download.freebsd.org/ftp/releases/powerpc/$arch/14.3-RELEASE/base.txz \
                | tar -xJf - -C $SYSROOT/freebsd/$arch 2>/dev/null &
            fi
          done

          openbsd=(amd64 arm64 riscv64)
          files=(base77 comp77)
          for arch in "${openbsd[@]}"; do
            if [ ! -d $SYSROOT/openbsd/$arch ]; then
              mkdir -p $SYSROOT/openbsd/$arch
              for file in "${files[@]}"; do
                curl -fsSL https://cdn.openbsd.org/pub/OpenBSD/7.7/$arch/$file.tgz | tar -xzf - -C $SYSROOT/openbsd/$arch 2>/dev/null &
              done
            fi
          done

          netbsd=(amd64 evbarm-aarch64)
          files=(base comp etc)
          for arch in "${netbsd[@]}"; do
            if [ ! -d $SYSROOT/netbsd/$arch ]; then
              mkdir -p $SYSROOT/netbsd/$arch
              for file in "${files[@]}"; do
                curl -fsSL https://cdn.netbsd.org/pub/NetBSD/NetBSD-10.1/$arch/binary/sets/$file.tar.xz | tar -xJf - -C $SYSROOT/netbsd/$arch 2>/dev/null &
              done
            fi
          done

          if [ ! -f $SYSROOT/dfly-x86_64-6.4.2_REL.iso ]; then
            curl -fsSL https://mirror-master.dragonflybsd.org/iso-images/dfly-x86_64-6.4.2_REL.iso.bz2 | bunzip2 -c > $SYSROOT/dfly-x86_64-6.4.2_REL.iso &
            mkdir -p $SYSROOT/dfly
          fi

          if [ ! -d sysroot/omnios ]; then
            curl -fsSL https://downloads.omnios.org/media/stable/omnios-r151054.zfs.xz | xz -d > sysroot/omnios-r151054.zfs
            ls -hl sysroot/omnios*
            mkdir -p sysroot/omnios
          fi

          wait
          chmod -R u+rwX "$SYSROOT"

          sudo mount -o loop $SYSROOT/dfly-x86_64-6.4.2_REL.iso $SYSROOT/dfly

          sudo zpool create -O mountpoint=sysroot/omnios omnios sysroot/omnios-r151054.zfs
          sudo zpool import -o altroot=sysroot/omnios omnios

          ls -ahl sysroot/omnios

          targets=(
            x86_64-unknown-illumos
            x86_64-unknown-dragonfly
            x86_64-unknown-freebsd
            aarch64-unknown-freebsd
            riscv64gc-unknown-freebsd
            powerpc64-unknown-freebsd
            powerpc64le-unknown-freebsd
            x86_64-unknown-openbsd
            aarch64-unknown-openbsd
            riscv64gc-unknown-openbsd
            x86_64-unknown-netbsd
            aarch64-unknown-netbsd
          )

          for target in ${targets[@]}; do
            time cargo s --target $target
          done

          sudo umount $SYSROOT/dfly

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  "x86_64-unknown-dragonfly DragonFly-x86_64"
                  "x86_64-unknown-freebsd FreeBSD-x86_64"
                  "aarch64-unknown-freebsd FreeBSD-aarch64"
                  "riscv64gc-unknown-freebsd FreeBSD-riscv64"
                  "powerpc64-unknown-freebsd FreeBSD-ppc64"
                  "powerpc64le-unknown-freebsd FreeBSD-ppc64le"
                  "x86_64-unknown-openbsd OpenBSD-x86_64"
                  "aarch64-unknown-openbsd OpenBSD-aarch64"
                  "riscv64gc-unknown-openbsd OpenBSD-riscv64"
                  "x86_64-unknown-netbsd NetBSD-x86_64"
                  "aarch64-unknown-netbsd NetBSD-aarch64"
          )
          for target in "${targets[@]}"; do
            read -r arch name <<< "$target"
            echo "Uploading $name..."
            mv target/$arch/src/Img target/$arch/src/$name || true
            gh release upload Nightly target/$arch/src/$name --clobber || true
          done
