name: uwp

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  macOS:
    name: uwp
    runs-on: ubuntu-26.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Ubuntu apt update and install
        run: |
          # (sudo apt install gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 g++-mingw-w64-x86-64 g++-mingw-w64-i686  binutils-mingw-w64-all mingw-w64-ucrt64-dev && touch ~/apt.finish) &>/dev/null &

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: C/C++ sccache wrappers
        run: |
          set -euo pipefail

          mkdir -p "sccache-bin"

          for compiler in clang clang++ gcc g++; do
            cat > "sccache-bin/$compiler" <<EOF
          #!/bin/bash
          exec sccache /usr/bin/$compiler "\$@"
          EOF
            chmod +x "sccache-bin/$compiler"
          done

          echo "$PWD/sccache-bin" >> "$GITHUB_PATH"

      - name: Zig toolchain install
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Build Release
        run: |
          cargo update
          set +e -x

          # time {
          #     set +x
          #     while [[ ! -e freebsd/armv7 ]]; do
          #         sleep 1
          #     done
          # }

          curl -fsSL https://cdimage.debian.org/cdimage/ports/stable/hurd-i386/debian-hurd.img.tar.gz | tar -xzvf -

          LOOP=$(sudo losetup --find --show --partscan debian-hurd.img)
          echo "$LOOP"
          lsblk -f "$LOOP"
          sudo fdisk -l "$LOOP"
          sudo mkdir -p /mnt/hurd
          sudo mount -t ext2 -o ro /dev/loop0p1 /mnt/hurd

          targets=(
            i686-unknown-hurd-gnu
          )
          for target in ${targets[@]}; do
            time cargo s $target
          done

          exit

          find ./target -iname img.exe -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(

          )

          for target in "${targets[@]}"; do
            IFS='-' read -r arch vendor os abi <<< "$target"
            if [[ "$vendor" == "win7" ]]; then
                name="${os^}-${arch}-${abi}-${vendor}"
            elif [[ -n "$abi" ]]; then
                name="${os^}-${arch}-${abi}"
            else
                name="${os^}-${arch}"
            fi
            name="${name}.exe"
            echo "Uploading $name..."
            mv target/$target/src/{img.exe,$name}|| true
            gh release upload Nightly --clobber target/$target/src/$name || true
          done
