name: Yocto

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"
  IMAGE: ghcr.io/${{ github.repository }}
  YOCTO: "6.0.3"

jobs:
  Linux:
    name: Yocto/OpenEmbedded
    runs-on: ubuntu-26.04

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: setup-oras
        uses: oras-project/setup-oras@v2

      - name: Login GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Toolchain downloads
        run: |
          IMAGE="${IMAGE,,}"
          url=https://downloads.yoctoproject.org/releases/yocto/yocto-${YOCTO}/toolchain/x86_64
          files=(
          poky-glibc-x86_64-core-image-sato-core2-64-genericx86-64-toolchain-${YOCTO}.sh
          poky-glibc-x86_64-core-image-sato-armv8a-genericarm64-toolchain-${YOCTO}.sh
          poky-glibc-x86_64-core-image-sato-cortexa8hf-neon-beaglebone-yocto-toolchain-${YOCTO}.sh
          poky-glibc-x86_64-core-image-sato-riscv64imafdc-qemuriscv64-toolchain-${YOCTO}.sh
          )
          set -o pipefail
          mkdir -p "/opt/poky/$YOCTO"
          if digest=$(oras manifest fetch --format go-template --template '{{ (index .content.layers 0).digest }}' "${IMAGE}:yocto${YOCTO}" 2>/dev/null); then
            echo "Yocto: $digest"
            oras blob fetch --output=- "${IMAGE}@${digest}" | tar --zstd -xf - -C "/opt/poky/$YOCTO"
          else
            mkdir -p /home/runner/yocto
            for file in "${files[@]}"; do
                path="/home/runner/yocto/$file"
                if [[ ! -f "$path" ]]; then
                    curl -LsSf "$url/$file" -o "$path"
                    chmod +x "$path"
                fi
                echo | "$path"
            done
            rm -f /home/runner/yocto/*
            sudo tar --zstd -C /opt/poky/$YOCTO -cf /tmp/yocto${YOCTO}.tar.zst .
            oras push --disable-path-validation "${IMAGE}:yocto${YOCTO}" "/tmp/yocto${YOCTO}.tar.zst:application/vnd.wyvern.yocto.tar.zstd"
          fi

      - name: Build Release
        run: |
          cargo update
          set +e -x

          targets=(
            "aarch64-oe-linux-gnu environment-setup-armv8a-poky-linux"
            "armv7-oe-linux-gnueabihf environment-setup-cortexa8hf-neon-poky-linux-gnueabi"
            "riscv64-oe-linux-gnu environment-setup-riscv64imafdc-poky-linux"
            "x86_64-oe-linux-gnu environment-setup-core2-64-poky-linux"
          )

          sdk=/opt/poky/${YOCTO}
          ln -s $sdk/sysroots sysroots

          for entry in "${targets[@]}"; do
            read -r target env <<< "$entry"
            (
            source $sdk/$env &>/dev/null
            unset RUST_TARGET_PATH
            for v in ${!CARGO_TARGET_@}; do
                unset "$v"
            done
            export PATH="$HOME/.cargo/bin:$PATH" &>/dev/null
            time cargo s $target
            )
          done

          find ./target -iname img -type f | xargs ls -hl
          lscpu
          free -m

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
                  aarch64-oe-linux-gnu
                  armv7-oe-linux-gnueabihf
                  riscv64-oe-linux-gnu
                  x86_64-oe-linux-gnu
          )
          for target in "${targets[@]}"; do
            IFS='-' read -r arch vendor os abi rest <<< "$target"
            if [[ -n "$abi" ]]; then
                if [[ "$vendor" == "openwrt" ]]; then
                    name="${vendor^}-${arch}-${abi}"
                elif [[ "$vendor" == "oe" ]]; then
                    name="OpenEmbedded-${arch}-${abi}"
                else
                    if [[ "$abi" == "ohos" ]]; then
                        name="Android-${arch}-${abi}"
                    else
                        name="${os^}-${arch}-${abi}"
                    fi
                fi
            else
                if [[ "$os" == "androideabi" ]]; then
                    name="Android-${arch}"
                else
                    name="${os^}-${arch}"
                fi
            fi

            echo "Uploading $name..."
            mv target/$target/src/{img,$name} || true
            gh release upload Nightly --clobber target/$target/src/$name || true
          done
