name: Zig-linux

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  macOS:
    name: Zig-linux
    runs-on: ubuntu-26.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Ubuntu apt update and install
        run: |
          (sudo apt install binutils-mingw-w64 binutils-mingw-w64-i686 gcc-mingw-w64 gcc-mingw-w64-i686 binutils-mingw-w64-x86-64-ucrt binutils-mingw-w64-i686-ucrt && touch ~/apt.finish) &>/dev/null &

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
          targets: i686-pc-windows-gnu,x86_64-pc-windows-gnu

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: C/C++ sccache wrappers
        run: |
          set -euo pipefail

          mkdir -p "sccache-bin"

          for compiler in clang clang++ gcc g++; do
            cat > "sccache-bin/$compiler" <<EOF
          #!/bin/bash
          exec sccache /usr/bin/$compiler "\$@"
          EOF
            chmod +x "sccache-bin/$compiler"
          done

          echo "$PWD/sccache-bin" >> "$GITHUB_PATH"

      - name: Zig toolchain install
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Build Release
        run: |
          cargo update
          set +e -x

          time (
              set +x
              while [[ ! -f ~/apt.finish ]]; do
                  sleep 1
              done
          )

          # hexagon-unknown-linux-musl
          # cargo s x86_64-unknown-illumos
          # cargo s aarch64_be-unknown-linux-gnu_ilp32
          # cargo s aarch64-unknown-linux-gnu_ilp32

          # mkdir -p csky && curl -fsSL 'https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource/1356021/1619528643136/csky-linux-gnuabiv2-tools-x86_64-glibc-linux-4.9.56-20210423.tar.gz' | tar -xz -C csky --strip-components=1

          # time cargo s csky-unknown-linux-gnuabiv2
          # time cargo s csky-unknown-linux-gnuabiv2hf

          targets=(
          i686-pc-windows-gnu
          i686-win7-windows-gnu
          x86_64-pc-windows-gnu
          x86_64-win7-windows-gnu
          )
          for target in ${targets[@]}; do
            time cargo s $target
          done
          exit

          targets=(
            aarch64_be-unknown-linux-gnu
            aarch64_be-unknown-linux-musl
            armeb-unknown-linux-gnueabi
            powerpc-unknown-openbsd
            powerpc-unknown-netbsd
            mipsel-unknown-netbsd
            armv7-unknown-netbsd-eabihf
            armv6-unknown-netbsd-eabihf
          )

          for target in ${targets[@]}; do
            time cargo s $target &
          done
          wait
          find ./target -type f -name "img" -exec ls -hl {} \;
          sw_vers
          hostinfo
          sysctl -n machdep.cpu.brand_string

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
            armeb-unknown-linux-gnueabi
            aarch64_be-unknown-linux-gnu
            aarch64_be-unknown-linux-musl
            powerpc-unknown-openbsd
            powerpc-unknown-netbsd
            mipsel-unknown-netbsd
            armv7-unknown-netbsd-eabihf
            armv6-unknown-netbsd-eabihf
          )

          for target in "${targets[@]}"; do
            IFS='-' read -r arch vendor os abi <<< "$target"
            first="$(printf '%s' "$os" | cut -c1 | tr '[:lower:]' '[:upper:]')"
            rest="${os#?}"
            os_cap="${first}${rest}"
            if [[ -n "$abi" ]]; then
                name="${os_cap}-${arch}-${abi}"
            else
                name="${os_cap}-${arch}"
            fi
            echo "Uploading $name..."
            mv target/$target/src/{img,$name} || true
            gh release upload Nightly --clobber target/$target/src/$name || true
          done
