name: Zig-build

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  macOS:
    name: Zig linker
    runs-on: macos-26

    steps:
      - name: Disable macos spotlight index
        run: |
          sudo mdutil -a -i off
          sudo mdutil -a -d
          sudo pmset -a powernap 0
          sudo pmset -a sleep 0

      - name: Checkout
        uses: actions/checkout@v6

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Zig toolchain install
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Build Release
        run: |
          cargo update
          set +e -x

          #hexagon-unknown-linux-musl

          targets=(
            aarch64_be-unknown-linux-gnu
            aarch64_be-unknown-linux-musl
            powerpc-unknown-openbsd
            mipsel-unknown-netbsd
            armv7-unknown-netbsd-eabihf
          )

          for target in ${targets[@]}; do
            time cargo s $target
          done

          find ./target -type f -name "img" -exec ls -hl {} \;
          sw_vers
          hostinfo
          sysctl -n machdep.cpu.brand_string

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
            aarch64_be-unknown-linux-gnu
            aarch64_be-unknown-linux-musl
            powerpc-unknown-openbsd
            mipsel-unknown-netbsd
            armv7-unknown-netbsd-eabihf
          )

          for target in "${targets[@]}"; do
            IFS='-' read -r arch vendor os abi <<< "$target"
            first="$(printf '%s' "$os" | cut -c1 | tr '[:lower:]' '[:upper:]')"
            rest="${os#?}"
            os_cap="${first}${rest}"
            if [[ -n "$abi" ]]; then
                name="${os_cap}-${arch}-${abi}"
            else
                name="${os_cap}-${arch}"
            fi
            echo "Uploading $name..."
            mv target/$target/src/img target/$target/src/$name || true
            gh release upload Nightly --clobber target/$target/src/$name || true
          done
