name: Zig-build

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "on"
  RUSTC_WRAPPER: "sccache"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  macOS:
    name: Zig linker
    runs-on: ubuntu-26.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-workspace-crates: "true"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@main

      - name: Zig toolchain install
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Install LLVM
        run: |
          ver=23
          if [ "$ver" = "23" ]; then
              wget https://apt.llvm.org/llvm.sh
              chmod +x llvm.sh
              sudo ./llvm.sh $ver
          fi
          for x in clang clang++ lld; do
            sudo update-alternatives --install "/usr/bin/$x" "$x" "/usr/bin/$x-$ver" 200
          done
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/lld-$ver 200

      - name: Build Release
        run: |
          cargo update
          set +e -x

          # hexagon-unknown-linux-musl
          # cargo s x86_64-unknown-illumos
          # cargo s powerpc64-unknown-linux-gnuelfv2
          # exit

          targets=(
            aarch64_be-unknown-linux-gnu
            aarch64_be-unknown-linux-musl
            armeb-unknown-linux-gnueabi
            powerpc64-unknown-linux-musl
            powerpc-unknown-openbsd
            powerpc-unknown-netbsd
            mipsel-unknown-netbsd
            armv7-unknown-netbsd-eabihf
            sparc64-unknown-netbsd
            sparc64-unknown-openbsd
          )

          for target in ${targets[@]}; do
            time cargo s $target
          done

          find ./target -type f -name "img" -exec ls -hl {} \;
          sw_vers
          hostinfo
          sysctl -n machdep.cpu.brand_string

      - name: Rust Versions
        run: rustup -V; cargo -Vv; rustc -Vv

      - uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: |
            target/**/img*
            !target/**/*.d
          if-no-files-found: ignore

      - name: Upload binaries to a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          targets=(
            armeb-unknown-linux-gnueabi
            powerpc64-unknown-linux-musl
            aarch64_be-unknown-linux-gnu
            aarch64_be-unknown-linux-musl
            powerpc-unknown-openbsd
            powerpc-unknown-netbsd
            mipsel-unknown-netbsd
            armv7-unknown-netbsd-eabihf
          )

          for target in "${targets[@]}"; do
            IFS='-' read -r arch vendor os abi <<< "$target"
            first="$(printf '%s' "$os" | cut -c1 | tr '[:lower:]' '[:upper:]')"
            rest="${os#?}"
            os_cap="${first}${rest}"
            if [[ -n "$abi" ]]; then
                name="${os_cap}-${arch}-${abi}"
            else
                name="${os_cap}-${arch}"
            fi
            echo "Uploading $name..."
            mv target/$target/src/{img,$name} || true
            gh release upload Nightly --clobber target/$target/src/$name || true
          done
